### PR TITLE
Rename LazyAdamOptimizer to LazyAdam

### LINKED ISSUE #104: Rename LazyAdamOptimizer to LazyAdam
All core optimizers in TensorFlow 2.0 dropped the "Optimizer" suffix: "Adam", "Adadelta", etc. (see the [module overview](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/optimizers)). For consistency, optimizers defined in tensorflow/addons should probably follow the same naming convention.

So I propose to rename `LazyAdamOptimizer` to `LazyAdam`.

### PR DESCRIPTION
**Pull request by Squadrick**
Fixes #104

### CODE REVIEW

**Comment by facaiy** [comment]
Thanks, Dheeraj, Armando!
 Let's merge it after Sean approves the change cc @seanpmorgan

**Comment by Squadrick** [comment]
@armando-fandango I formatted the python file, it should pass the tests now.

**Comment by Squadrick** [comment]
@facaiy 

On `lazy_adam_test.py` line 217. If I run `yapf` it formats the line in a way that fails in `pylint`.

**Comment by facaiy** [comment]
Dheeraj, do you take `make code-format` and `make sanity-check` a try ?https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#development-environment

By the way, we always squash all commits into one commit before merging, so it seems not necessary to rebase our commits :-) . (rebase is kind of dangerous and not friendly for reviewer).

**Comment by facaiy** [comment]
What pylint error? You can disable it temporarily https://github.com/tensorflow/addons/blob/master/STYLE_GUIDE.md

**Pull request merged**
