### PR TITLE
Bump TF 2.3.1

### PR DESCRIPTION
**Pull request by WindQAQ**
Bump TF 2.3.1

### CODE REVIEW

**Review by bhack — COMMENTED** [review]
Is this going to break https://github.com/tensorflow/addons/blob/master/tools/update_release_version.sh?

**Comment by WindQAQ** [comment]
> Is this going to break https://github.com/tensorflow/addons/blob/master/tools/update_release_version.sh?

Oops, I don't even notice that we have this amazing tool. And yes, it will break it.

**Comment by bhack** [comment]
> > Is this going to break https://github.com/tensorflow/addons/blob/master/tools/update_release_version.sh?
> 
> Oops, I don't even notice that we have this amazing tool. And yes, it will break it.

Do you think It could be extended to cover this?

**Comment by WindQAQ** [comment]
It's not so easy...
But seems that we have never published the wheel again patch versioned tensorflow so we should discuss if we should let this PR go forward.

**Comment by bhack** [comment]
> It's not so easy...
> But seems that we have never published the wheel against patch versioned tensorflow so we should discuss if we should let this PR go forward.

This was cause generally wed didn't have Tensorflow patch releases but this case was about security fixes.

**Comment by WindQAQ** [comment]
So, should we modify that script to make it compatible with multiple versions?

**Comment by bhack** [comment]
Yes

**Comment by WindQAQ** [comment]
Let me close it first as I don't have good implementation of that script in mind.

**Comment by bhack** [comment]
What strings we will have on 2.4.0 release?

**Comment by WindQAQ** [comment]
We usually pin to rc version first.

**Comment by bhack** [comment]
Yes I meant to expand regular expression I think we need to figure out what strings we need to handle. After this change what strings we will need to maintain? Need we need to handle arbitrary list of releases e.g. 2.3.0,2.3.1,2.4.0rc etc..

**Comment by WindQAQ** [comment]
> Need we need to handle arbitrary list of releases e.g. 2.3.0,2.3.1,2.4.0rc etc..

Yes

**Comment by bhack** [comment]
Only in tf-version right? Are the single entries  just the first element of this list?

**Comment by WindQAQ** [comment]
> Only in tf-version right? Are the single entries just the first element of this list?

Yes, I think so.

**Pull request closed without merging**
