### PR TITLE
rename ImageProjectiveTransform to ImageProjectiveTransformV2

### PR DESCRIPTION
**Pull request by jharmsen**
Rename addon op ImageProjectiveTransform to ImageProjectiveTransformV2.

This ensures the op names are consistent between addon and contrib (see #86).

### CODE REVIEW

**Comment by jharmsen** [comment]
Thank you very much!  What would the next steps be for rebuilding the pip package with this change? 
(We're hoping to use this new package in a Udacity module next week.)

**Comment by seanpmorgan** [comment]
We can build a 0.1.1 version and publish it this weekend if that works. Just a note we're still working on our MacOS and Windows compatibility so that might need to be a disclaimer in the course. (Hoping to have that figured out by a 0.2 or 0.3 release)

**Comment by jharmsen** [comment]
Thanks for the quick review!  Building a new 0.1.1 version would be excellent.  Let me know if I should open an issue or anything to track it.

**Comment by seanpmorgan** [comment]
@jharmsen 0.1.1 has been released to pypi. Thanks for your help!

**Pull request merged**
