### PR TITLE
Move examples directory out of source directory #221

### PR DESCRIPTION
**Pull request by shashvatshahi1998**

### CODE REVIEW

**Comment by shashvatshahi1998** [comment]
#221

**Comment by shashvatshahi1998** [comment]
@facaiy  There was some issue so I closed that pr and added this one

**Comment by shashvatshahi1998** [comment]
Also I am facing issue in deleting old examples file

**Comment by shashvatshahi1998** [comment]
In my branch it is shown already deleted god knows why whenever I am doing cd tensorflow_addons/examples it is showing no path exists so can you please tell me why it is so?

**Comment by shashvatshahi1998** [comment]
Please @facaiy can you review it?

**Comment by WindQAQ** [comment]
Hi @shashvatshahi1998 , you've not removed `tensorflow_addons/examples` yet :-)

**Comment by shashvatshahi1998** [comment]
@WindQAQ  thats what I asked that whenever I am trying to access that in my forked repository it is shown that there is no examples in tensorflow_addons

**Comment by WindQAQ** [comment]
Could you screenshot the output for the command `git status`?

**Comment by shashvatshahi1998** [comment]
@WindQAQ is there any way  I can remove that file from my github dashboard directly as I wanted to do git rm -f examples but it is showing inaccessible in my case.

**Comment by shashvatshahi1998** [comment]
Thanks @seanpmorgan for removing that file but now it is showing cla: No , why?

**Comment by seanpmorgan** [comment]
I'm sorry I didn't see you two were working on this and I just pushed a commit to the branch. I can override the CLA... it has issue when theres two authors.

Apologies that would have been a good learning chance. You can still try to revert my commit and recreate it just for practice

**Comment by seanpmorgan** [comment]
Thanks for the PR @shashvatshahi1998 !

**Comment by shashvatshahi1998** [comment]
Thanks @seanpmorgan

**Pull request merged**
