### PR TITLE
:arrow_up: linting dependencies

### PR DESCRIPTION
**Pull request by lgeiger**
# Description

This PR updates the linting dependencies and reformats the code accordingly.

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running Black + Flake8
    - [x] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

### CODE REVIEW

**Review by manzilz — DISMISSED** [review]

**Comment by bhack** [comment]
We need to check https://github.com/tensorflow/addons/issues/2666

**Comment by lgeiger** [comment]
> We need to check #2666

I'll rebase onto #2635 once merged since it will fix the CI failures due to the Keras/TF version mismatches

**Comment by bhack** [comment]
Yes but we need to reanable sk* tests

**Comment by lgeiger** [comment]
> Yes but we need to reanable sk* tests

Correct, however this PR only touches linting dependencies, so sk* tests shouldn't be affected at all. I rebased it onto `master` let's see what CI thinks.

**Comment by bhack** [comment]
> > Yes but we need to reanable sk* tests
> 
> Correct, however this PR only touches linting dependencies, so sk* tests shouldn't be affected at all. I rebased it onto `master` let's see what CI thinks.

Ok if we are not touching any other python 3.10 wheels here I will merge it when the CI pass.

**Review by bhack — APPROVED** [review]

**Pull request merged**
