### PR TITLE
FIX: Correctly link the new soname for tf2

### PR DESCRIPTION
**Pull request by seanpmorgan**
Bit of a moving target here... but at least the soname is correct for tf2-preview now

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Also a question for @av8ramit and @karmel :

Last night the nightlies failed for 3/4 of our builds. The one that passed ran on `tf_nightly_2.0_preview-2.0.0.dev20190402-cp34-cp34m-manylinux1_x86_64.whl`,

 while the others ran on `tf_nightly_2.0_preview-2.0.0.dev20190403-cp27-cp27mu-manylinux1_x86_64.whl`

Is there anyway to delay the jobs we currently have by say 20min-1hr?

**Comment by qlzh727** [comment]
Also @gunan

**Comment by karmel** [comment]
I will push back the nightlies by 1 hour.

**Comment by karmel** [comment]
Sorry, to clarify-- do we want to delay the jobs or make them run earlier? The one that passed was the one that ran with the prior day's TF build (ie, the earliest of the addons runs).

**Comment by seanpmorgan** [comment]
I believe delay so that they all would have failed. I'm not positive but my read was that one of the jobs got launched before the nightly was finished pushing to pypi

**Comment by karmel** [comment]
The time delay was submitted, and should get picked up with the next build.

**Pull request merged**
