### PR TITLE
RELEASE: 0.5.2

### LINKED ISSUE #541: Package TFA 0.5.2 pinned to TF2-RC2
RC2 is released so we can do a minor release pinned to this. For now this is blocked until #539 is merged.

### PR DESCRIPTION
**Pull request by facaiy**
close #541

### CODE REVIEW

**Comment by guillaumekln** [comment]
TensorFlow 2.0 final has just been released. Should it be used for this new version?

**Comment by facaiy** [comment]
> TensorFlow 2.0 final has just been released. Should it be used for this new version?

Good new, Guillaume! Of course, thank you for reminding me 😄

**Comment by bionicles** [comment]
i'm eager [no pun intended] to play with the Lookahead + RAdam combo, can't wait!

**Comment by facaiy** [comment]
@bionicles Agreed. I filed an issue https://github.com/tensorflow/addons/issues/553 to track 0.6 release, please subscribe it

**Pull request merged**
