### PR TITLE
[WIP]  Add failing test case for image dataset transforms

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Initial attempt at getting test coverage for #243

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
OK, so I've rebased this PR off of #330.  I can confirm that the failing test case is now passing.

**Comment by kyleabeauchamp** [comment]
For sanity, we probably don't want to review this until #330 is merged.

**Comment by facaiy** [comment]
Looks good, Kyle. As we add test case for unknown shape tensor, is it necessary to retain
 tf.data.Dataset test case? What do you think?

**Comment by kyleabeauchamp** [comment]
Yeah it's probably a bit redundant, but the main value is adding a test
that covers the reported use case.

**Comment by facaiy** [comment]
Make sense to me as well, but I prefer to make unit test simple according to Occam's Razor. How about letting us add test case with tf.data.Dataset later when we think it necessary?

**Comment by kyleabeauchamp** [comment]
Sgtm, I'm fine with closing this ticket.

**Pull request closed without merging**
