### PR TITLE
add implementation of Octave Convolution layers

### PR DESCRIPTION
**Pull request by amascia**
Hi,
This pull request is an implementation of the octave convolutional layers introduced by Chen et al. in [this paper](http://openaccess.thecvf.com/content_ICCV_2019/papers/Chen_Drop_an_Octave_Reducing_Spatial_Redundancy_in_Convolutional_Neural_Networks_ICCV_2019_paper.pdf).
I originally created [a pull request](https://github.com/tensorflow/tensorflow/pull/38154) on the tensorflow repository and I was told that this one might be a better fit for this feature.
I gave additional information on these new layers in [a tensorflow issue](https://github.com/tensorflow/tensorflow/issues/37576) that you might want to check. I also attached a python file to give you an example usage of OctaveConv2D, OctaveConv2DTranspose and OctaveConvAdd on the MNIST dataset.
Thank you very much for your work and I hope I'll hear from you soon.
 
[AchilleMascia_mnist_octconv2D_2DTranspose.py.zip](https://github.com/tensorflow/addons/files/4580865/AchilleMascia_mnist_octconv2D_2DTranspose.py.zip)

### CODE REVIEW

**Comment by bhack** [comment]
Thank you for this contribution.
Just an extra question from our template:
> - Is there already an implementation in another framework? (if so, where):

Just as a side question, do you plan to contribute in your roadmap also the "generalized version" of the Octoconv?

**Comment by gabrieldemarmiesse** [comment]
Many thanks for the pull request, it seems too big to review all at once. Could you make a first pull request just for one layer, and after it's reviewed and merged, you can make other pull requests for other layers. Reviewing 2000 lines of code at once is not realistic for us :) You can also run the pre-commit to ensure that you won't have problems with the CI .

**Comment by AchilleMascia** [comment]
@bhack thank you for you comment and sorry I missed that bullet point from your template. There is an MXNet implementation by facebook research [here](https://github.com/facebookresearch/OctConv), the repository also contains a list of third-party unofficial implementations (pytorch, MXNet and keras). It is my understanding that neither of them have implementations of octave convolutions in 3D nor octave convolution transpose 2D / 3D.
When you say the "generalized version of the Octoconv" do you mean the abstract OctaveConv class I implemented in the octave_convolutional.py file ? If that's the case, I am of course willing to contribute it to the repo.

@gabrieldemarmiesse thank you for your comment. I wouldn't want to review a 2000 line pull request all at once either. Is it okay for you if I split it in three ?
The first one would have OctaveConv (abstract class), OctaveConvAdd and OctaveConv1D with the tests. The second one would have OctaveConv2D and OctaveConv3D (+ tests) and the third one OctaveConv2DTranspose and OctaveConv3DTranspose (+ tests).
Once you have reviewed the first one, the other two shouldn't be difficult since the layers are really similar with the 1D one.
How does this look to you ?
I'll run the pre-commit before pushing for the next PRs !

**Comment by gabrieldemarmiesse** [comment]
For the first pull request, please make the OctaveConv1D with it's abstract class, without the OctaConvAdd. Don't expose it in the `__init__.py` so that's it's not public until all the layers (2D and 3D) are there.

**Comment by bhack** [comment]
For "generalzied" octave convolution I meant https://arxiv.org/abs/2003.05643

**Comment by AchilleMascia** [comment]
@gabrieldemarmiesse Ok, I will do that.

@bhack I haven't checked the generalized octave convolution, I will try it and get back to you with it if promising

**Comment by bhack** [comment]
@AchilleMascia Ok, sorry I don't know if you was confused by the "generalizzation" term cause there was also a Google paper with that term related to Octave convolution at https://arxiv.org/abs/2002.10032

**Comment by seanpmorgan** [comment]
Closing as this is being broken up into more managable PRs for review.

**Pull request closed without merging**
