### PR TITLE
Added Mean_filter_2D

### PR DESCRIPTION
**Pull request by Mainak431**

### CODE REVIEW

**Comment by Mainak431** [comment]
<<<<<<< patch-7
| mean_filter_2d | @Mainak431 | mainakdutta76@gmail.com |
=======
>>>>>>> master
| median_filter_2d | @Mainak431 | mainakdutta76@gmail.com |

This is showing as conflict. I dont understand why. I have included both the submodules mean_filter_2d and median_filter_2d. I have not replaced the second with the first. If anybody understand how to resolve this conflict, please help.

**Comment by facaiy** [comment]
Mainak, I think this is a conflict between your PR branch and the latest master branch. You need to fetch the latest master branch, and resolve the merge conflict. 

- [Resolving a merge conflict using the command line](https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line)
- [Google: git resolve merge conflict](https://www.google.com/search?client=firefox-b&ei=jhWvXPOhOom4sgXm8a7ADA&q=git+resolve+merge+conflict&oq=git+resolve+merge+conflict)

**Comment by Mainak431** [comment]
Done

**Comment by seanpmorgan** [comment]
@Mainak431 there should be several merge conflicts after #184 . Could you please restructure when time allows. Thanks.

**Comment by Mainak431** [comment]
Closing this PR. Opened restructured one at #185

**Pull request closed without merging**
