### PR TITLE
Update Readme.md for median_filter_2D

### PR DESCRIPTION
**Pull request by Mainak431**

### CODE REVIEW

**Comment by Mainak431** [comment]
Readme for #111 . @seanpmorgan

**Comment by seanpmorgan** [comment]
Thanks @Mainak431 looks good, but before I merge would you like to be the submodule maintainer for median filtering? It would just mean that questions or changes to the submodule would be directed to you for comment.

**Comment by Mainak431** [comment]
@seanpmorgan No problem there.

**Comment by seanpmorgan** [comment]
Great can you please ad your name and contact info to this README? See https://github.com/tensorflow/addons/tree/master/tensorflow_addons/layers for an example

**Comment by Mainak431** [comment]
Done

**Pull request merged**
