### PR TITLE
Improve the AttentionMechanism base class

### PR DESCRIPTION
**Pull request by guillaumekln**
# Description

The `AttentionWrapper` takes `AttentionMechanism` instances as arguments. However, it used methods that were not defined in the `AttentionMechanism` base class.

This PR improves the base class definition with the actual interface expected by `AttentionWrapper`.

## Type of change

- [ ] Bug fix
- [ ] New Tutorial
- [x] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Activation and the changes conform to the [activation contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md#contribution-guidelines)
- [ ] New Callback and the changes conform to the [callback contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/README.md#contribution-guidelines)
- [ ] New Image addition and the changes conform to the [image op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md#contribution-guidelines)
- [ ] New Layer and the changes conform to the [layer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/README.md#contribution-guidelines)
- [ ] New Loss and the changes conform to the [loss contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/README.md#contribution-guidelines)
- [ ] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)
- [ ] New Optimizer and the changes conform to the [optimizer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/README.md#contribution-guidelines)
- [ ] New RNN Cell and the changes conform to the [rnn contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/README.md#contribution-guidelines)
- [x] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [ ] New Text addition and the changes conform to the [text op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/README.md#contribution-guidelines)

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

Ran the existing tests.

### CODE REVIEW

**Review by seanpmorgan — APPROVED** [review]
Refactor LGTM and I don't see any other need for `self._memory_initialized`. @qlzh727 any issues with merging?

**Comment by qlzh727** [comment]
Thanks for the update and sorry for the late reply.

The concern I have for this PR is that the implementation of the attention is now split into two classes, especially self.key and self.value are created by used in two different class. When only looking at the AttentionMechanism, it is hard to reason about what is the self.key/value, unless we look at how they are initialized in _BaseAttentionMechanism.setup_memory().

If you feel AttentionMechanism should declare more methods for AttentionWrapper to use, maybe we should just create them but still keep the implementation in _BaseAttentionMechanism?

**Comment by guillaumekln** [comment]
Thanks for the comment.

The initial observation was that `AttentionWrapper` expected a `_BaseAttentionMechanism` and not a `AttentionMechanism`. So my idea was to move some methods in the base class to fix this inconsistency and at the same time make it easier for users to write custom attention mechanisms. By following this route, would it be enough to define a base implementation of `setup_memory` in `AttentionMechanism` to clarify how the attributes are initialized?

Or do you think it's better for `AttentionMechanism` to just be the interface?

**Comment by qlzh727** [comment]
I guess the AttentionWrapper won't work if user just implement the method in AttentionMechanism, so I would expect _BaseAttentionMechanism to just graduate to be a public class to override. Maybe we should just rename the _BaseAttentionMechanism and remove the AttentionMechanism?

**Comment by guillaumekln** [comment]
Ok, let's rename `_BaseAttentionMechanism` to `AttentionMechanism`. I will make a new PR. Thanks!

**Pull request closed without merging**
