### PR TITLE
Sprite image creator for Tensorboard.

### PR DESCRIPTION
**Pull request by bono1567**
A function which builds sprite-images for Projector plug-in in Tensorboard.

### CODE REVIEW

**Comment by facaiy** [comment]
Hi, welcome and thank you for the PR. Could you explain why we need it, or where it come from (tf.contrib?)?

**Comment by bono1567** [comment]
Hello @facaiy , this feature will be used to create sprite images which can be used in the tensorboard. Currently, we have to build sprite images by coding it every time we use the projector plugin in tensorboard.
Each sprite image represents an embedding.

Please go through this article for more details about embeddings, projector plugin and sprite image usage.
[https://www.tensorflow.org/guide/embedding](url)

**Comment by seanpmorgan** [comment]
Thanks @bono1567. I agree this is useful and is even described in an official guide. I just want to pull in some tensorboard members to see if they agree that this functionality makes sense in addons.

@tensorflow/tensorboard-team is this functionality not planned on any roadmap that you are aware of? And does Addons seem like the appropriate place?

**Comment by seanpmorgan** [comment]
cc @nfelt @stephanwlee . Not sure if the tensorboard-team mention actually pings anyone.

**Comment by nfelt** [comment]
This appears to be related to https://github.com/tensorflow/tensorboard/issues/1984.

@bono1567 if you'd like to contribute this functionality specifically for the TensorBoard projector use case, then it would make more sense for it to live in the TensorBoard repo alongside the `visualize_embeddings()` API here: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/__init__.py

Rather than adding more complexity to the `__init__.py` I think it would make sense to move visualize_embeddings to a new `projector_api.py` file in the same directory, add the sprite image creator to that file (and add the tests to `projector_api_test.py`).

**Comment by seanpmorgan** [comment]
Thanks Nick! Closing this PR as it seems there's a more intuitive home in `tensorboard/plugins/projector/projector_api.py`. 

Thanks for the PR though @bono1567 ..the code looked quite good and hope you'll return to addons again in the future!

**Comment by bono1567** [comment]
Will look into it. Thanks @nfelt 
Thanks @seanpmorgan .

**Pull request closed without merging**
