### PR TITLE
Make Rectified Adam faster

### PR DESCRIPTION
**Pull request by szutenberg**
by moving common tensors to `_prepare_local`

# Description

Brief Description of the PR:
This patch implements `_prepare_local` which is used in other optimizers too. For example [LAMB](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/lamb.py).

This patch improves performance because common values are computed only once per training step.

## Type of change

- [x] Bug fix

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running pre-commit hooks

# How Has This Been Tested?

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
`pytest tensorflow_addons/optimizers/tests/rectified_adam_test.py`

### CODE REVIEW

**Comment by CyberZHG** [comment]
> /cc @CyberZHG Are you still available as Codeowner?

No.

**Comment by bhack** [comment]
@szutenberg Do you want to be the new codeowner of Rectified Adam? 

/cc @seanpmorgan

**Comment by szutenberg** [comment]
@bhack Yes, I'll be glad to be a new codeowner of Rectified Adam. Thanks!

**Comment by bhack** [comment]
Ok please edit the in this PR https://github.com/tensorflow/tensorflow/blob/master/CODEOWNERS

**Comment by szutenberg** [comment]
@bhack  Done: https://github.com/tensorflow/addons/pull/2570/commits/d1d9be6ccf6b7497e393c5ba5afbbc32b96b4bd7

**Comment by bhack** [comment]
@szutenberg How much is faster with the precomputed coeffs?

**Comment by szutenberg** [comment]
@bhack  - do you have any doubts that this change is necessary? It makes graphs much smaller. Performance boost should be visible on CPU, especially when tensors are small and we have many variables to optimize. I found this issue when running custom workload on my custom accelerator and it improved step time by few ms.

I see that CI is failing on `KeyError: "User 'shreyashpatodia' line 151 does not exist. Did you make a typo?` (CODEOWNERS). I can be also a codeowner of stochastic_weight_averaging and novograd. Is it ok for you?

**Comment by bhack** [comment]
> I see that CI is failing on KeyError: "User 'shreyashpatodia' line 151 does not exist. Did you make a typo? (CODEOWNERS). I can be also a codeowner of stochastic_weight_averaging and novograd. Is it ok for you?

No is that the user account doesn't exist anymore on Github and the codeowner check doesn't support this specific use case:
https://github.com/tensorflow/addons/blob/fbf79940d294dd84e8ffc452abb331a01bee5aff/.github/workflows/notify_codeowners.py#L52-L55

So if you are interested you could add yourself as the codeowner of these two as they are orphan.

**Comment by szutenberg** [comment]
@bhack Done https://github.com/tensorflow/addons/pull/2570/commits/db7e28056f82d11ea4b2254a131016a4a2c1c0dc

**Comment by seanpmorgan** [comment]
Thanks @szutenberg !

**Pull request merged**
