### PR TITLE
Apple silicon support

### LINKED ISSUE #2503: tensorflow-addons doesn't work with tensorflow-macos
**Describe the feature and the current behavior/state.**
On my Mac with M1, on which [TensorFlow 2.5 for Mac](https://developer.apple.com/metal/tensorflow-plugin/) is installed, `pip install tensorflow-addons` fails with this error:

```
% pip install tensorflow-addons
ERROR: Could not find a version that satisfies the requirement tensorflow-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-addons
```

Here's the output of `pip list`:
```
% pip list
Package                 Version
----------------------- -------------------
...
tensorboard-plugin-wit  1.8.0
tensorflow-estimator    2.5.0
tensorflow-macos        2.5.0 <--
tensorflow-metal        0.1.1
termcolor               1.1.0
...
```

**Relevant information**
- Are you willing to contribute it (yes/no): maybe
*If you wish to contribute, then read the requirements for new contributions in [`CONTRIBUTING.md`](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#requirements-for-new-contributions-to-the-repository)*
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where): no
- Does the relavent academic paper exceed 50 citations? (yes/no): n/a
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where): setup.py

**Who will benefit with this feature?**
Users of TensorFlow for Mac.

**Any other info.**

### PR DESCRIPTION
**Pull request by tetsuyasu**
# Description

Brief Description of the PR: Apple silicon support.

Fixes #2503

## Type of change

- [x] Bug fix
- [ ] New Tutorial
- [ ] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Activation and the changes conform to the [activation contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md#contribution-guidelines)
- [ ] New Callback and the changes conform to the [callback contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/README.md#contribution-guidelines)
- [ ] New Image addition and the changes conform to the [image op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md#contribution-guidelines)
- [ ] New Layer and the changes conform to the [layer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/README.md#contribution-guidelines)
- [ ] New Loss and the changes conform to the [loss contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/README.md#contribution-guidelines)
- [ ] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)
- [ ] New Optimizer and the changes conform to the [optimizer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/README.md#contribution-guidelines)
- [ ] New RNN Cell and the changes conform to the [rnn contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/README.md#contribution-guidelines)
- [ ] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [ ] New Text addition and the changes conform to the [text op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/README.md#contribution-guidelines)

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

The steps are as follows. 

## create python virtual environment
(I installed python 3.9.5 with pyenv and pyenv-virtualenv.)

## install tensorflow
pip install tensorflow-macos
pip install tensorflow-metal

## install bazel 3.7.2
xcode-select --install || echo OK
export BAZEL_VERSION=3.7.2
curl -fLO "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh"
chmod +x "bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh"
./bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh --user
(set the PATH to bazel)

## install tensorflow-addons
git clone -b mywork https://github.com/tetsuyasu/addons.git/
cd addons
python3 ./configure.py
bazel build build_pip_pkg
pip install pathlib
bazel-bin/build_pip_pkg artifacts
pip install artifacts/tensorflow_addons-*.whl

### CODE REVIEW

**Review by tetsuyasu — COMMENTED** [review]
It doesn't affect builds on other platforms.
Following the way the original code, I left the versions hard-coded.

**Review by bhack — APPROVED** [review]

**Comment by mbui0327** [comment]
I follow your instruction to build from source. But got the following error when running `bazel-bin/build_pip_pkg artifacts`.
Do you know why?

```running install_scripts
Traceback (most recent call last):
  File "/private/var/folders/gx/80ykqyq96qq66n6_r20tzywr0000gn/T/tmp.XXXXXXXXXX.BHApfHJa/setup.py", line 81, in <module>
    setup(
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/Users/bachbui/miniforge3/envs/py38tf/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_10_13_x86_64')
+ true
+ cp 'dist/*.whl' /Users/bachbui/works/addons/artifacts
cp: dist/*.whl: No such file or directory
```

**Comment by tetsuyasu** [comment]
Are you using an intel mac?

In your error messages, "macosx_10_13_x86_64" is found.

In the build script (addons/build_deps/build_pip_pkg.sh), m1 mac uses "macosx_11_0_arm64", intel mac uses "macosx_10_13_x86_64".

    if [[ x"$(arch)" == x"arm64" ]]; then
      BUILD_CMD="${BUILD_CMD} --plat-name macosx_11_0_arm64"
    else
      BUILD_CMD="${BUILD_CMD} --plat-name macosx_10_13_x86_64"
    fi

**Comment by mbui0327** [comment]
Hmm, no, my machine is M1 Mac. Because of M1 that I have to resort to source build for addons.
Something wrong here?

**Comment by mbui0327** [comment]
Indeed `echo $(arch)` returns `i386`. But I am 100% sure my Mac is M1. Just bought it few months ago :)

**Comment by mbui0327** [comment]
My fault, I ran the term in Rosetta mode and `arch` return i386. Thanks.

**Comment by schr476** [comment]
I'm having an error with: 
`build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')`

**Comment by bhack** [comment]
> I'm having an error with:
> `build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')`

/cc @lgeiger

**Comment by lgeiger** [comment]
@bhack sounds like pip doesn't recognize the MacOS version tag. Can you try updating via `python -m pip install pip wheel setuptools --upgrade` and try again?

**Comment by myz1912** [comment]
`AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')` 
I got this as well. I'm using MacOS 12 with M1 pro chip

**Pull request merged**
