### PR TITLE
 Remove custom op activations

### PR DESCRIPTION
**Pull request by seanpmorgan**
# Description

Brief Description of the PR:
Removed deprecated custom op activations

Part of https://github.com/tensorflow/addons/issues/2122

Closes https://github.com/tensorflow/addons/issues/1775

## Type of change

- Removed deprecated custom op activations

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [x] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] This PR contains modifications to C++ custom-ops

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Note I've pushed the gelu deprecation to 0.13 since it will first appears as keras.activations.gelu in TF2.4

**Review by WindQAQ — APPROVED** [review]
LGTM! Thanks!

**Comment by bhack** [comment]
With this I think that we have just few custom_ops kernel in the repository...

**Review by bhack — APPROVED** [review]

**Comment by WindQAQ** [comment]
Just a side note here. I remember that @penpornk https://github.com/tensorflow/tensorflow/pull/33945#issuecomment-625380208 said that we can keep the implementation and use kernel selection very long time ago. Not sure if it's still needed.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent_v2.py#L722-L845

**Comment by seanpmorgan** [comment]
> Just a side note here. I remember that @penpornk [tensorflow/tensorflow#33945 (comment)](https://github.com/tensorflow/tensorflow/pull/33945#issuecomment-625380208) said that we can keep the implementation and use kernel selection very long time ago. Not sure if it's still needed.
> 
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent_v2.py#L722-L845

Yeah I haven't heard anything more on this, but we can add the custom-ops back if someone understands this well and is willing to build it into Addons in a clean way. For now I think we stick with our deprecation plan.

**Pull request merged**
