### PR TITLE
fix bug in crf.CrfDecodeForwardRnnCell

### PR DESCRIPTION
**Pull request by tracy-talent**
When I read your code implementation of crf, I found a little bug in class CrfDecodeForwardRnnCell, check it!

### CODE REVIEW

**Comment by tracy-talent** [comment]
Get it! Thank you, I suggest updating the comment, it's easy to mislead.

**Comment by Squadrick** [comment]
Do you want to update it in this PR?

**Comment by tracy-talent** [comment]
> Do you want to update it in this PR?
Yes, I do. I suggest
```
state: A tuple containing a [batch_size, num_tags] matrix containing the 
        previous step's score values.
```
is better.

**Comment by Squadrick** [comment]
@tracy-talent Yup, it's what we should go with it.

**Pull request closed without merging**
