### PR TITLE
Add Kendall's Tau-c, Spearman's Rank, Pearson's Correlation metrics

### PR DESCRIPTION
**Pull request by nicolaspi**
# Description

Add Kendall's Tau-c, Spearman's Rank, Pearson's Correlation metrics.

## Type of change

- [X] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)

# Checklist:

- [X] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [X] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

The tests follows the contribution guidelines for metrics (https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines).
The metrics are tested against the scipy implementation counterpart.

### CODE REVIEW

**Review by sorensenjs — COMMENTED** [review]
This looks like a good change, but it's very hard to see the diffs - is it possible to either branch the file so that it shows diffs, or separate the renaming of the file from the other edits.

I'm not a frequent github user - if there's an easy way for me to see the diffs that would be helpful.

**Comment by nicolaspi** [comment]
There is no change _per se_. The original `KendallsTau` has been renamed `KendallsTauB` (to differenciate from `KendallsTauC`).

I have factored `update_state` from `KendallsTau` into a base class `CorrelationBase` with the abstract method `result`. For each metric, there is a concrete class that implements `result` with the corresponding metric's logic.

**Comment by nicolaspi** [comment]
@sorensenjs I changed the commit history to highlight the differences, this is the best I could come up with: https://github.com/tensorflow/addons/pull/2741/commits/b4977f41b44263406c84f28effb64428a2224200

**Review by sorensenjs — APPROVED** [review]
Thanks for the clarification. This is a nice generalization.

**Review by bhack — APPROVED** [review]

**Comment by bhack** [comment]
@nicolaspi Can you PR the codeowners file  to match this refactoring?

**Pull request merged**
