### PR TITLE
fix #1824

### LINKED ISSUE #1824: Cannot use random_cutout in keras training
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): 2.1 from pip
- TensorFlow-Addons version and how it was installed (source or binary): 0.9.1 from pip
- Python version: Python 3.6.10 (default, Dec 19 2019, 23:04:32) [GCC 5.4.0 20160609] on linux
- Is GPU used? (yes/no): yes

**Describe the bug**

Cannot use the `tfa.image.random_cutout` is `tf.keras.Sequential.fit`;

**Code to reproduce the issue**

This MWE works:

 ```
import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, GlobalMaxPooling2D, Flatten

@tf.function
def preprocessing(image):
    return tf.image.convert_image_dtype(image, tf.float32)


X = tf.cast(tf.random.uniform(shape=(10, 224, 224, 3), minval=0, maxval=255), tf.uint8)
y = tf.random.uniform(shape=(10,))
dataset = tf.data.Dataset.from_tensor_slices((X, y)).map(lambda x, y: (preprocessing(x), y)).batch(3)
model = Sequential([Conv2D(10, (3, 3)), GlobalMaxPooling2D(), Flatten(), Dense(1)])
model.compile(loss="mse", optimizer="adam")
model.fit(dataset)
```

When I try to add the random_cutout, ie:

```
@tf.function
def preprocessing(image):
    return tf.image.convert_image_dtype(tf.squeeze(tfa.image.random_cutout(tf.expand_dims(image, 0), mask_size=(20, 20))), tf.float32)
```

it fails

**Other info / logs**

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    model.fit(dataset)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 593, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 702, in __init__
    x = standardize_function(x)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 684, in standardize_function
    return dataset.map(map_fn, num_parallel_calls=dataset_ops.AUTOTUNE)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1591, in map
    self, map_func, num_parallel_calls, preserve_cardinality=True)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3926, in __init__
    use_legacy_function=use_legacy_function)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3147, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2395, in _get_concrete_function_internal
    *args, **kwargs)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3140, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py:677 map_fn
        batch_size=None)
    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py:2410 _standardize_tensors
        exception_prefix='input')
    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py:529 standardize_input_data
        data = [standardize_single_array(x) for x in data]
    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py:529 <listcomp>
        data = [standardize_single_array(x) for x in data]
    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py:451 standardize_single_array
        if (x.shape is not None and len(x.shape) == 1 and
    /home/clementw/Keras-FewShotLearning/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py:822 __len__
        raise ValueError("Cannot take the length of shape with unknown rank.")

    ValueError: Cannot take the length of shape with unknown rank.
```

### PR DESCRIPTION
**Pull request by fsx950223**
Sometimes miss Tensor shape in Graph mode.
Set shape explicitly.

### CODE REVIEW

**Comment by bhack** [comment]
Does `def cutout(` require `@tf.function` decoration?

**Comment by bhack** [comment]
@fsx950223 Do you have a minimal code to reproduce #1824?

**Comment by fsx950223** [comment]
Since Dataset runs map function in Graph mode. I won't add a test code.
You could try with reporter's minimal code.
The reason is that batch_size is None and after call ```tf.squeeze``` the Tensor shape misses.
I have to explicitly set shape.

**Comment by bhack** [comment]
Yes I saw that his squeeze example the Tensor shape misses.
Have you seen: https://github.com/tensorflow/addons/issues/1824#issuecomment-627944505

**Comment by fsx950223** [comment]
> Yes I saw that his squeeze example the Tensor shape misses.
> Have you seen: [#1824 (comment)](https://github.com/tensorflow/addons/issues/1824#issuecomment-627944505)

It won't change anything.

**Comment by bhack** [comment]
> It won't change anything.
Maybe it's useful to users but not ops.

This why I asked to you before what do you mean with "sometimes". 
Do you mean that Is the case when an user need to use tf.squeeze over the Op result? Or that tf.squeeze Is not working correctly?

**Comment by fsx950223** [comment]
> > It won't change anything.
> > Maybe it's useful to users but not ops.
> 
> This why I asked to you before what do you mean with "sometimes".
> Do you mean that Is the case when an user need to use tf.squeeze over the Op result? Or that tf.squeeze Is not working correctly?

We don't support 3D and 2D images after we discussed at https://github.com/tensorflow/addons/pull/1338#discussion_r396463720

**Comment by fsx950223** [comment]
How do you solve images with batch_size=2?

**Comment by bhack** [comment]
Ok for 3D and 2D images I've not followed that review but just the new thread at https://github.com/tensorflow/addons/issues/1825

**Pull request merged**
