### PR TITLE
Enhance configure: add supporting for customize pip index URL

### PR DESCRIPTION
**Pull request by howl-anderson**
User can set customized  pip index URL (pypi mirror) in configure process for accelerate python package downloading (more then 100M packages need be downloaded)

### CODE REVIEW

**Comment by facaiy** [comment]
Thanks for the change. How about using Interactive input, rather than passing argument, like [set_tf_download_clang](https://github.com/tensorflow/tensorflow/blob/949474a44831bc28bac8a97bdafd1f7dc6589a97/configure.py#L545)?

**Comment by howl-anderson** [comment]
@facaiy Cool idea! I will try to implement this feature in other PR.

**Comment by facaiy** [comment]
@howl-anderson Hi, Xiaoquan. I read https://pip.pypa.io/en/stable/user_guide/#config-file , and it seems not difficult to create a (and edit) configuration of pip, like this:

```bash
[global]
timeout = 60
index-url = http://pypi.douban.com/simple
trusted-host = pypi.douban.com
```

What do you think :-)

**Comment by facaiy** [comment]
If you'd like, welcome contribution about how to customize pip in the [contribution guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md).

**Comment by howl-anderson** [comment]
Hi @facaiy, there are two ways can configure pypi package source:
1. temporary use a package source
```bash
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package
```

2. set as default package source
for pip version >=10.0.0 :
```bash
pip install pip -U
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

I think both ways can be very useful depends on user's preference. I will update the [contribution guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md) to show how using those methods in details.

**Comment by facaiy** [comment]
> I will update the contribution guidelines to show how using those methods in details.

Great, and method 2 sounds better. Feel free to ping me when new doc PR is created :-) 
So might I close the PR? Always welcome contributors and thank all for your contributions!

**Comment by howl-anderson** [comment]
@facaiy I create a new PR #107 for this, please take a look.

**Pull request closed without merging**
