### PR TITLE
Supporting dynamic shape tensor in sparse_image_warp

### PR DESCRIPTION
**Pull request by comc35**
Hello,
I am resubmitting this PR here, addons, from [the previous PR](https://github.com/tensorflow/tensorflow/pull/30904).
The current version of `sparse_image_warp.py` only support static shaped tensors. 
This PR is for upgrading [`sparse_image_warp.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/sparse_image_warp.py) to support computations of tensor with dynamic shape. 
Updates of [`sparse_image_warp_test.py`](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/sparse_image_warp_test.py) is also included.

The functional test is also done with time_warping operation in SpecAugment which requires `sparse_image_warp`.

### CODE REVIEW

**Comment by WindQAQ** [comment]
LGTM. @comc35, would you mind addressing https://github.com/tensorflow/addons/issues/332 too? I do suppose dynamic shape tensor would benefit unknown shape compatibility. Maybe adding some unittests is necessary to verify the implementations. Many thanks for the contribution!

**Comment by WindQAQ** [comment]
Hi @comc35, could you update the PR? Thanks.

**Comment by gabrieldemarmiesse** [comment]
I'll close this pull request as it has been inactive for a while now. Feel free to comment if you want me to reopen the pull request.

**Comment by bhack** [comment]
Check https://github.com/tensorflow/io/issues/839#issuecomment-607362644

**Comment by lutzzz** [comment]
Any updates on this one @comc35?

**Pull request closed without merging**
