### PR TITLE
Add notifications for failing tests/builds

### PR DESCRIPTION
**Pull request by seanpmorgan**
Quick question: @ewilderj do you know if a travis server will be able to email that address without being in the google group?

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I checked the travis docs (https://docs.travis-ci.com/user/notifications/#configuring-email-notifications) and this seems consistent.  LGTM once green!

**Comment by ewilderj** [comment]
@seanpmorgan we ought to be able to directly add and whitelist the email address. hit me up once you know what the sender email address is

**Comment by seanpmorgan** [comment]
Hmmm marking this as WIP because it looks like travis may not email addresses that aren't registered on github. Will look into this a little more later

**Comment by seanpmorgan** [comment]
@ewilderj Could you please add `builds@travis-ci.com` to the google group (or whitelist). It seems we should be able to get this to work. 
https://github.com/travis-ci/travis-ci/issues/7169

I've temporarily added my email to the notifications so I can verify they're being sent at all.

**Comment by ewilderj** [comment]
> @ewilderj Could you please add `builds@travis-ci.com` to the google group (or whitelist). It seems we should be able to get this to work.
> [travis-ci/travis-ci#7169](https://github.com/travis-ci/travis-ci/issues/7169)
> 
> I've temporarily added my email to the notifications so I can verify they're being sent at all.

Done (for https://groups.google.com/a/tensorflow.org/forum/#!forum/addons-testing)

**Pull request merged**
