### PR TITLE
Focal loss-Fix minor bugs in reduction as well as #693

### PR DESCRIPTION
**Pull request by AakashKumarNain**

### CODE REVIEW

**Comment by AakashKumarNain** [comment]
This fixes #693 as well as another bug in reduction strategy.

**Comment by AakashKumarNain** [comment]
@Squadrick all checks have passed. Let's merge it then?

**Comment by AakashKumarNain** [comment]
@Squadrick Thanks 😄

**Comment by AakashKumarNain** [comment]
@Squadrick I checked that my name is not in the `maintainers` list for focal loss. Can we add it, please?

**Comment by Squadrick** [comment]
@AakashKumarNain Not sure what the policy on having multiple maintainers for a single module is (@seanpmorgan Just to make sure this is all cool?). Create a PR adding your name to the maintainers' list for `focal_loss`, we can continue the discussion there.

cc @SSaishruthi (the current maintainer) for visibility.

**Comment by seanpmorgan** [comment]
> @AakashKumarNain Not sure what the policy on having multiple maintainers for a single module is (@seanpmorgan Just to make sure this is all cool?). Create a PR adding your name to the maintainers' list for `focal_loss`, we can continue the discussion there.
> 
> cc @SSaishruthi (the current maintainer) for visibility.

Highly encourage multiple owners. Please feel free to submit a PR.

**Comment by AakashKumarNain** [comment]
Cool. I should have added it at the time I made the first commit for the focal loss but IIRC at that time, we didn't have the code owners/maintainers list. I will submit a new PR for it. Thanks, @seanpmorgan and @Squadrick

**Pull request merged**
