### PR TITLE
Failing to restore AdaBelief optimizer from checkpoint 

### PR DESCRIPTION
**Pull request by denadai2**
# Description

Brief Description of the PR: 
This PR solves the same issue reported in https://github.com/tensorflow/addons/issues/2361, by avoiding storing a int32 variable.

## Type of change

- [x] Bug fix

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running Black + Flake8
    - [x] By running pre-commit hooks

### CODE REVIEW

**Review by bhack — CHANGES_REQUESTED** [review]
You need to add the checkpoint test here as in:

https://github.com/tensorflow/addons/pull/2369/files

**Review by bhack — APPROVED** [review]

**Comment by denadai2** [comment]
Thanks @bhack! When do you think it will be possible to have a release of tensorflow addons so that it is possible to have AdaBelief in production? The nightly version might not be accepted in my company :) 

thx

**Comment by bhack** [comment]
You can subscribe to https://github.com/tensorflow/addons/pull/2696

**Comment by juntang-zhuang** [comment]
LGTM, thanks for fixing the problem.

**Pull request merged**
