### PR TITLE
run docker with current user

### PR DESCRIPTION
**Pull request by fsx950223**
Root user is annoyed and we should use current user.

### CODE REVIEW

**Comment by seanpmorgan** [comment]
I could go either way with this. Could you describe why you feel running as root user is a pain? 

- Need sudo to remove `.bazelrc`?
- Potential security risks?
- Other? 

My only hesitation is documentation bloat. If we do include this we'll probably want to edit it here as well:
https://github.com/tensorflow/addons/blob/master/tools/run_docker.sh#L94

@tensorflow/sig-addons-maintainers thoughts?

**Comment by fsx950223** [comment]
When I use ```make code-format```, it will change ownership to root.

**Comment by seanpmorgan** [comment]
> When I use `make code-format`, it will change ownership to root.

Thanks, that is a problem. Would you mind adding the user flag to the shell script I mentioned so we can confirm that this doesn't impact the CI testing from Kokoro

**Comment by fsx950223** [comment]
ok

Sean Morgan <notifications@github.com<mailto:notifications@github.com>> 于 2019年9月26日周四 下午8:35写道：

When I use make code-format, it will change ownership to root.

Thanks, that is a problem. Would you mind adding the user flag to the shell script I mentioned so we can confirm that this doesn't impact the CI testing from Kokoro

**Comment by fsx950223** [comment]
> > When I use `make code-format`, it will change ownership to root.
> 
> Thanks, that is a problem. Would you mind adding the user flag to the shell script I mentioned so we can confirm that this doesn't impact the CI testing from Kokoro

I just change the markdown and it won't impact the ci test. It's just an advice.

**Comment by seanpmorgan** [comment]
> > > When I use `make code-format`, it will change ownership to root.
> > 
> > 
> > Thanks, that is a problem. Would you mind adding the user flag to the shell script I mentioned so we can confirm that this doesn't impact the CI testing from Kokoro
> 
> I just change the markdown and it won't impact the ci test. It's just an advice.

Yes, I'm asking you to change the `run_docker.sh` as we recommend users to run the following command: `bash tools/run_docker.sh -c 'make code-format'`
https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#development-tips

**Comment by fsx950223** [comment]
> > > > When I use `make code-format`, it will change ownership to root.
> > > 
> > > 
> > > Thanks, that is a problem. Would you mind adding the user flag to the shell script I mentioned so we can confirm that this doesn't impact the CI testing from Kokoro
> > 
> > 
> > I just change the markdown and it won't impact the ci test. It's just an advice.
> 
> Yes, I'm asking you to change the `run_docker.sh` as we recommend users to run the following command: `bash tools/run_docker.sh -c 'make code-format'`
> https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#development-tips

I am sorry to have missed it. I rarely use it.

**Comment by fsx950223** [comment]
Too trouble.

**Comment by seanpmorgan** [comment]
> Too trouble.

Thanks anyways! Unfortunately we don't have a ton of control over the Kokoro runtime so when that failed its a bit difficult to dive into why it needed root

**Pull request closed without merging**
