### PR TITLE
Moved tests out of run_in_graph_and_eager_mode in interploate_spline

### PR DESCRIPTION
**Pull request by autoih**
cc @gabrieldemarmiesse

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
It seems you have conflicts. Could you fix them? Thanks!

**Comment by gabrieldemarmiesse** [comment]
It seems there are no changes in this pull request. Did you have an issue with git?

**Comment by autoih** [comment]
@googlebot I fixed it.

**Comment by autoih** [comment]
I closed this pr, and create a new one, since it's too messy.

**Pull request closed without merging**
