### PR TITLE
adding .DS_store to gitignore

### PR DESCRIPTION
**Pull request by SSaishruthi**
Is it ok if we add `.DS_store` to .gitignore file for convenience?

### CODE REVIEW

**Comment by facaiy** [comment]
How about using `.*` to ignore all hidden files?

**Comment by Squadrick** [comment]
@facaiy Yeah, sure. That seems like a better idea.

**Comment by seanpmorgan** [comment]
> How about using `.*` to ignore all hidden files?

I previously removed that ignore because `.travis.yml` are you okay with more specific ignores?

**Comment by SSaishruthi** [comment]
Is that change ok or I need to change something?

**Comment by facaiy** [comment]
> > How about using `.*` to ignore all hidden files?
> 
> I previously removed that ignore because `.travis.yml` are you okay with more specific ignores?

Sean, I prefer to ignore all hidden files by default, and then we can use `git add --force .yourfile` to add whatever file we need. What do you think?

**Comment by seanpmorgan** [comment]
> > > How about using `.*` to ignore all hidden files?
> > 
> > 
> > I previously removed that ignore because `.travis.yml` are you okay with more specific ignores?
> 
> Sean, I prefer to ignore all hidden files by default, and then we can use `git add --force .yourfile` to add whatever file we need. What do you think?

That works for me. Currently we have only 1 tracked hidden file anyway. @SSaishruthi can you please edit this PR to ignore all hidden files and then we can merge

**Comment by Gokkulnath** [comment]
@seanpmorgan  Why dont we add a explicit include .travis.yml using ! prefix ?? That way you need not remember to force add it.  Check here for more info https://git-scm.com/docs/gitignore 
we just need to add \!.travis.yml to gitignore

**Comment by seanpmorgan** [comment]
> @seanpmorgan Why dont we add a explicit include .travis.yml using ! prefix ??
> we just need to add !.travis.yml to gitignore
> That way you need not remember to force add it. Check here for more info https://git-scm.com/docs/gitignore

That sounds great. Thanks @Gokkulnath !

**Comment by SSaishruthi** [comment]
@seanpmorgan I have made changes based on my understanding. Is that ok?

**Pull request merged**
