### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PRUBHTEJ**
Corrected a grammatical error

### CODE REVIEW

**Comment by PRUBHTEJ** [comment]
@shreyashpatodia , can you please approve this PR?

**Comment by seanpmorgan** [comment]
> I am not a native speaker, but maybe it is either "it comprises two main components" or "it is made up of two main components".
> 
> https://www.merriam-webster.com/dictionary/comprise

Yeah very nit picky PR here, but if we want to correct the grammar [then @WindQAQ is correct](
https://whatis.techtarget.com/feature/Comprises-or-is-comprised-of#:~:text=To%20comprise%20means%20to%20contain.&text=It%20seems%20simple%20enough%3A%20%E2%80%9Cto,Usually.)

**Comment by PRUBHTEJ** [comment]
Done the changes @WindQAQ .
Requesting for a review.

**Comment by PRUBHTEJ** [comment]
> Thank you

My pleasure!!

**Pull request merged**
