### PR TITLE
add bazel command to generate API docs

### LINKED ISSUE #46: Generate API docs
As our repository matures it's important to have api docs to improve user experience. As discussed in #38 we will also be able to remove the table of contents off the main README.

Should we host on https://readthedocs.org/ or is there something else recommended @ewilderj @dynamicwebpaige @karmel ?

### PR DESCRIPTION
**Pull request by facaiy**
Fix #46
Related PRs: #140, #195, #196

```bash
bazel build tools/docs:build_docs
bazel-bin/tools/docs/build_docs --git_branch=master --output_dir=docs/api_docs/python/
```

I push the documnets generated to my repository, and everyone can preview it at https://github.com/facaiy/addons/blob/tf_addons_doc_preview/docs/api_docs/python/tfa.md

### CODE REVIEW

**Comment by facaiy** [comment]
It's still not perfect, I think there are at least two problems, take [tf_addons.activations](https://github.com/facaiy/addons/blob/tf_addons_doc_preview/docs/api_docs/python/tf_addons/activations.md) as an example:
1. we need to filter those members of `__futures__` module: `absolute_import`, `division`, `print_function`.
2. tensorflow_docs cannot recognize `tf.function` function: `sparsemax`.

@lamberta @MarkDaoust Hi, can we find a better way to solve those problems?

**Comment by facaiy** [comment]
Gently ping @lamberta @MarkDaoust

**Comment by facaiy** [comment]
@seanpmorgan Sean, do we need to generate api documents for 0.3 release?

**Comment by lamberta** [comment]
@yashk2810 recently added https://github.com/tensorflow/docs/commit/5afa33995ec952f4da5bf5855e3a0efd1cc5b08c that should filter out a few more.
Yash, can you look into the other issues in this PR? Thanks

**Comment by facaiy** [comment]
Thank you, Billy, I'll take a try today

**Comment by MarkDaoust** [comment]
So for those three questions:

1. Should be fixed.
2. The simplest fix is to patch in tensorflow's version of the `tf_inspect` module, since `tf.function` is following the `tf_decorator`protocol. 

```
from tensorflow_docs.api_generator import parser
from tensorflow.python.util import tf_inspect

 # Use tensorflow's `tf_inspect`, which is aware of `tf_decorator`.
parser.tf_inspect = tf_inspect
```

3. It's not clear that blocking all `__dunder__` symbols is the right answer.  The simplest way to block a single symbol is to just delete it from the module before running the doc generator `del tf_addons.__version__`. Passing `private_map={'tf_addons',['__version__']}` to the constructor would also work. If you need a more powerful filter you can add a callback to the list "callbacks=[public_api.local_definitions_filter]".

**Comment by facaiy** [comment]
@MarkDaoust Awesome, it works. Thanks for your help, Mark!

**Comment by facaiy** [comment]
@seanpmorgan @tensorflow/sig-addons-maintainers Hi, we can preview the document at https://github.com/facaiy/addons/blob/tf_addons_doc_preview/docs/api_docs/python/tfa.md

Could you take a look? And I think we can use it to generate API doc for 0.3 release.

**Comment by seanpmorgan** [comment]
@facaiy This looks great, thanks for getting this done it is much needed. My only question would be how do we intend to upload the docs on the release branch given the .gitignore? We could modify the .gitignore on the release branch?

Other than that LGTM for merging

**Comment by facaiy** [comment]
> My only question would be how do we intend to upload the docs on the release branch given the .gitignore? 

We have to use `git add -f doc` to do it explicitly on the release branch. I'm worried that someone might add doc into master branch inadvertently, that's why we put `/doc/` in the gitignore file.

**Pull request merged**
