### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by WindQAQ**
Per https://github.com/tensorflow/addons/pull/1980

### CODE REVIEW

**Comment by facaiy** [comment]
> Sounds good to me. Should we revert the change and add the warning?

Tzu-wei, sorry, I think you're right. Let's revert #1980 and remove the argument after next release, what do you think?

**Comment by WindQAQ** [comment]
> > Sounds good to me. Should we revert the change and add the warning?
> 
> Tzu-wei, sorry, I think you're right. Let's revert #1980 and remove the argument after next release, what do you think?

Sure. Let's do it.

**Comment by AakashKumarNain** [comment]
LGTM! Thanks. I didn't weighed in #1980 because IMO end user would always use core image ops as a ref, hence for the end user that argument shouldn't have been in there in the first place. Sorry for overlooking it though.

**Comment by AakashKumarNain** [comment]
@WindQAQ I think we can merge this now or are there any more changes that need to be made?

**Comment by WindQAQ** [comment]
Sure let's merge it :-)

**Pull request merged**
