### PR TITLE
DOC: use logo for SIG/addons

### PR DESCRIPTION
**Pull request by facaiy**
Thank @ewilderj :-)

### CODE REVIEW

**Comment by facaiy** [comment]
Totally agreed. How about the new one? Dose it look better?

**Comment by seanpmorgan** [comment]
@facaiy I clipped some of the whitespace around the text and uploaded a local file so we don't need to worry about the link. If you like the image better, should we merge it into community or is the static file in repo okay?

**Comment by facaiy** [comment]
I prefer public url to static file in the repo, but both are fine. And I'm afraid svg format cannot play well with markdown, while png format perhaps is better for web :-)

**Comment by facaiy** [comment]
Sean, I'd like to leave it up to you :-)

**Comment by seanpmorgan** [comment]
So I think we'll meet somewhere in the middle. I do think SVG is preferred format for web, but to be fair that wasn't a true svg graphic, just an image imported into svg. 

I'm uncomfortable with the URL link as it's outside of our control and could be broken without our knowledge. So PNG in repo I think is a good middle ground. I could live with the URL link, but I think it needs to be cropped anyway.

**Pull request merged**
