### PR TITLE
Moved test out of run_in_graph_and_eager_mode in triplet_test

### PR DESCRIPTION
**Pull request by autoih**
cc @gabrieldemarmiesse.

### CODE REVIEW

**Comment by autoih** [comment]
@gabrieldemarmiesse, I'm not sure why having issue related to bazel, ` ... Use the --test_verbose_timeout_warnings command line option to see which ones these are.` Do you have any suggestions?

**Comment by gabrieldemarmiesse** [comment]
If you scroll in the logs, you'll see the stacktrace. It looks like a flaky test. We should have increased the absolute and relative tolerance to `1e-6`. Also be aware that the build of the master branch is currently broken because we use too much disk space. So you may experience failed builds because of that until we fix it.

**Comment by lc0** [comment]
The change itself looks reasonable to me. Thanks for updating @autoih 

Just to cross link to original one - https://github.com/tensorflow/addons/issues/1328

**Comment by gabrieldemarmiesse** [comment]
And thanks @lc0 for the review!

**Comment by gabrieldemarmiesse** [comment]
@googlebot I consent.

**Comment by seanpmorgan** [comment]
@googlebot I consent.

**Pull request merged**
