### PR TITLE
Added serializability tests in all optimizers and fixed serializability bug in yogi

### PR DESCRIPTION
**Pull request by ashutosh1919**
Related to #1294 .

@gabrieldemarmiesse - Please review this one.

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@seanpmorgan , I think the method you suggested is too constrained.  
I am checking this `serialization.check_config(new_optimizer.get_config(), optimizer, False)` and it is giving error as `AttributeError: 'ConditionalGradient' object has no attribute '__name__'`. What do it mean by that?

**Comment by ashutosh1919** [comment]
@seanpmorgan ,Please take a look at latest commit. With the use of `check_config()` in `serialization.py`, I have modified only one file and its tests - `conditional_gradient.py` and `conditional_graident_test.py` files. I have also slightly modified the function `check_config()`. Please review these three files and guide me whether I am doing right or not?

**Comment by seanpmorgan** [comment]
Hi @ashutosh1919 so the bazel tests are failing because you have to explicitly link python imports that are not in the same directory. See https://github.com/tensorflow/addons/pull/1740 as a fix or we can merge master into this branch after it merges.

**Comment by seanpmorgan** [comment]
@googlebot I consent.

**Comment by seanpmorgan** [comment]
> @seanpmorgan , I think the method you suggested is too constrained.
> I am checking this `serialization.check_config(new_optimizer.get_config(), optimizer, False)` and it is giving error as `AttributeError: 'ConditionalGradient' object has no attribute '__name__'`. What do it mean by that?

Ah, this is a bit too restrictive. Could you revert your commits using the shared serialization check please. I'll create an issue to standardize all optimizer serialization checks, but want to get the bugfix in, using your first serialization check.

**Comment by ashutosh1919** [comment]
@seanpmorgan - I have reverted the changes. And please create a separate issue to add serailizability check for optimizers in `serialization.py`. I definitely want to work on it.

**Pull request merged**
