### PR TITLE
Moved test out of run_in_graph_and_eager_mode in multihead_attention.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
See #1328

### CODE REVIEW

**Comment by cgarciae** [comment]
@gabrieldemarmiesse it seems there are 2 PRs open for this :worried:

**Comment by gabrieldemarmiesse** [comment]
@cgarciae really? My bad there are so many. What the other one?

**Comment by cgarciae** [comment]
This one I think: https://github.com/tensorflow/addons/pull/1436

**Comment by gabrieldemarmiesse** [comment]
Different tests functions are modified in both if I'm not mistaken.

**Pull request closed without merging**
