### PR TITLE
Bump dependency to tf2.2rc4

### PR DESCRIPTION
**Pull request by seanpmorgan**
Also want to troubleshoot what is going on with broken master branch

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Blocked by missing macos py38 whl for ttf2.2rc4

**Comment by gabrieldemarmiesse** [comment]
@bhack we can support multiple versions simultaneously. Here the oldest and more recent versions are the same, so it's trivial with a Ctrl+R. Even in the cases where we have multiple tf version, I'm not sure it's worth the effort to write a bash script.

**Comment by bhack** [comment]
It was just that we need to manually track 5 files every RC..

**Comment by seanpmorgan** [comment]
> @bhack we can support multiple versions simultaneously. Here the oldest and more recent versions are the same, so it's trivial with a Ctrl+R. Even in the cases where we have multiple tf version, I'm not sure it's worth the effort to write a bash script.

> It was just that we need to manually track 6 files every RC..

I do want to remove the version number from the contribution docs if possible so we don't need to update them constantly. 

Ctrl+R is pretty straightforward, but I agree there are ways to streamline this. Open to PRs, but not high priority

**Pull request merged**
