### PR TITLE
[WIP]  LookAhead fix for mixed

### PR DESCRIPTION
**Pull request by jonpsy**
# Description

Brief Description of the PR:
A naive solution.

Fixes # (issue)
#2403

I still think delegating the ```_hyper``` dictionary of the inner optimizer(in our case Rectified Adam) would be a better solution, but I'm getting an infinite loop in that case. That'd be the best solution imo, I'd like to discuss how to fix that.

A few test fails as of now

### CODE REVIEW

**Comment by jonpsy** [comment]
Hi @reedwm I really like your [approach](https://github.com/tensorflow/addons/issues/2332#issuecomment-754999736)  on this. However, I face two problems

1. If we relay our ```_hyper``` dict to the internal_optimizer (say RectifiedAdam), then we will lose our original ```_hyper``` dict. For ex: In LookAhead the original ```_hyper``` dict has these two params ```sync_period``` and ```slow_step_size```.
2. I went ahead and did it anyway, and I got maximum recursion depth reached error.

```
  File "/home/psykik/PycharmProjects/addons/tensorflow_addons/optimizers/lookahead.py", line 175, in _hyper
    return self._optimizer.hyper
  File "/home/psykik/PycharmProjects/addons/venv/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 788, in __getattribute__
    return super(OptimizerV2, self).__getattribute__(name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by reedwm** [comment]
Hmmm, I suspected delegating `_hyper` might be iffy. I will take a look next week and try to come up with a solution.

A public API to expose hyperaparameters would fix this, as then LossScaleOptimizer could use that API instead of using `_hyper`, and Lookahead could override the API. But it's much better to avoid adding a public API if possible.

**Comment by jonpsy** [comment]
Acked, but the LossScaleOptimizer is inside the official tensorflow repo. Imo, there's no cleaner way of doing it without meddling with the official repo. 

I have a stand-in solution though, how about we add another hyper parameter named ```learning_rate``` to the ```LookAhead```. Basically, it's a copy of the ```learning_rate``` parameter of the internal_optimizer, and we will update both of them parallely.  This way ```learning_rate``` hyper param will be found inside the ```_hyper``` dict of LookAhead.

**Comment by bhack** [comment]
I've just triggered the CI to investigate side effects on tests with https://github.com/tensorflow/tensorflow/pull/47449

**Comment by jonpsy** [comment]
All the tests should pass.

My approach:

1) Create a stand-in hyperparameter inside ```LookAhead``` class, with the same name ```learning_rate```. This way ```learning_rate``` will be found in ```_hyper``` dictionary.

2) Override the __set_attr__ of the OptimizerV2.py inside LookAhead so that it sets the ```learning_rate``` of the internal optimizer.

**Comment by reedwm** [comment]
The issue with creating a `learning_rate` hyperparameter in Lookahead is that setting the Lookahead learning rate does not change the original optimizer's learning rate. For example, try running the following with this PR:

```python
import tensorflow as tf
import tensorflow_addons as tfa

orig_optimizer = tf.keras.optimizers.Adam(learning_rate=0.002)
optimizer = tfa.optimizers.Lookahead(orig_optimizer)
optimizer = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
print(optimizer.lr)  # 0.001
print(orig_optimizer.lr)  # 0.002
optimizer.learning_rate = 0.003
print(optimizer.lr)  # 0.003
print(orig_optimizer.lr)  # 0.002
```

In this case, `orig_optimizer.lr` is the actual learning rate that will be used during training, but setting `optimizer.lr` does not affect `orig_optimizer.lr`. This means the LearningRateSchecduler will have no impact.

I'll try to come up with a workaround, but I dont have any yet. /CC @omalleyt12 let me know if you have any ideas

**Comment by jonpsy** [comment]
This is why I've overriden the set attribute, so that it changes both of them. Very well, shall I add this test case?

**Comment by reedwm** [comment]
Unfortunately, overriding `__setattr__` doesn't work, since LossScaleOptimizer delegates \_\_setattr\_\_ to call `self._optimizer._set_hyper_` instead of `self._optimizer.__setattr__`. See [here](https://github.com/tensorflow/tensorflow/blob/19c6728118c25f02f4a6fa754ca53ca6aa1044e4/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py#L919-L921).

Perhaps overriding `_set_hyper` in Lookahead, similar to what you do in `__setattr__`, would work.

**Comment by jonpsy** [comment]
Interesting..... I'll try that . Parallelly, bhack is working on fixing it in the official repo itself. So all our hardworking maybe for naught, haha.

**Comment by jonpsy** [comment]
Closing this PR in favor of  tensorflow/tensorflow#47449

**Pull request closed without merging**
