### PR TITLE
Add tf.Variable into TensorLike type

### PR DESCRIPTION
**Pull request by howl-anderson**
Add tf.Variable into TensorLike type (`tensorflow_addons/utils/types.py`)

### CODE REVIEW

**Comment by howl-anderson** [comment]
@autoih Can you review this PR for me? Thank you!

**Comment by gabrieldemarmiesse** [comment]
Looks good to me, I believe we could add tf.SparseTensor too, but it can be added in another pull request.

**Comment by autoih** [comment]
Thanks @howl-anderson. Please submit another PR with the suggestion as @gabrieldemarmiesse mentioned.

**Comment by howl-anderson** [comment]
@gabrieldemarmiesse @autoih Sure! When it's ready, I will let you know.

**Pull request merged**
