### PR TITLE
Make tests compatible with graph mode

### PR DESCRIPTION
**Pull request by WindQAQ**
1. Do TODO : make tests compatible with graph mode in distort_image_ops.
2. Revert #257. 
3. Have to use `self.evaluate()` to make exception raised in C++.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I think this all LGTM.  The only question I have is whether we need to do anything more along the lines of  to #260 / #290

**Comment by WindQAQ** [comment]
Hi Kyle, initial codes migrated from contrib have only dynamic shape checking (check in graph building time). When decorating with `tf.function`, they randomly failed the CI testing (I don't know the reason...). As suggested in https://github.com/tensorflow/addons/issues/260#issuecomment-494902359, doing static shape checking and dynamic shape checking seem to be the most robust and most correct way (see https://github.com/tensorflow/addons/issues/260#issuecomment-494886404 for more details).

**Comment by facaiy** [comment]
Tzh-Wei, what will happen without self.evaluate?

**Comment by WindQAQ** [comment]
Hi, Facai, without `self.evaluate`, the test will fail in graph mode because the OpError is not raised.

**Comment by Squadrick** [comment]
@WindQAQ Looks good, let's get this merged.

**Pull request merged**
