### PR TITLE
Improve AttentionWrapper compatibility with TF 2.0

### LINKED ISSUE #128: Make tfa.seq2seq.AttentionWrapper 2.0 compatible
The `AttentionWrapper` class is currently not compatible with TF2.0:

* it extends `tf.compat.v1.nn.rnn_cell.RNNCell` instead of `tf.keras.layers.AbstractRNNCell`
* it uses `tf.compat.v1.layers.Dense` instead of `tf.keras.layers.Dense`
* attention layers are saved in a `tuple` instead of a `list` which prevent them to be tracked

I can contribute to this change, unless this is a WIP by @qlzh727.

### PR DESCRIPTION
**Pull request by guillaumekln**
* Inherit from `tf.keras.layers.AbstractRNNCell`
* Replace `tf.compat.v1.layers.Dense` by `tf.keras.layers.Dense`
* Store sublayers in `list` instead of `tuple`

Closes #128

### CODE REVIEW

**Comment by qlzh727** [comment]
Thanks for the update. Looks great.

**Comment by qlzh727** [comment]
I will run the tests again to filter out any flaky test.

**Comment by seanpmorgan** [comment]
I believe we'll need to wait for #135 to merge for tests to pass

**Comment by seanpmorgan** [comment]
@guillaumekln @qlzh727 CI tests are back. Looks good but some minor linting issues if you could please fix and we can merge

**Comment by guillaumekln** [comment]
The lint issues are from #72. Do we want to fix them in this PR or in another one?

**Comment by qlzh727** [comment]
I think somehow the linter failed to detect that the object is a layer now (callable). We can address the issue in separate PR I think.

**Comment by seanpmorgan** [comment]
So trying to understand why this didn't fail after #72 then? Bazel caching? I'm hesitant to merge this without a fix PR first because all subsequent PRs in Addons will fail for lint and we'll need to review the logs. 

Could we prioritize a PR to fix the issue ahead of this one? I'm okay with a pylint-ignore as long as the linter is incorrect.

**Comment by guillaumekln** [comment]
Ok, let's pass another PR first that silences these warnings.

**Pull request merged**
