### PR TITLE
Adding badge for Sanity check

### PR DESCRIPTION
**Pull request by karmel**
The test itself is failing right now as per the comments in #68 , but here are the badge links for the Readme when ready.

### CODE REVIEW

**Comment by facaiy** [comment]
Karmel, I cannot reproduce the failure. What image are you using? And could you print the path before opening it?

**Comment by facaiy** [comment]
Gently ping @karmel @av8ramit

**Comment by av8ramit** [comment]
@facaiy sorry I did not have cycles to look into this this week. Would you like the exact commands being run internally?

**Comment by facaiy** [comment]
Amit, would you mind taking a look #68?

**Comment by av8ramit** [comment]
@facaiy I fixed [it](https://source.cloud.google.com/results/invocations/9997a63d-d0a3-4e55-b93c-3354878be2d7/targets).

**Comment by av8ramit** [comment]
You can merge this now @karmel the preview looks good.

**Comment by karmel** [comment]
Awesome— thanks, Amit.

**Pull request merged**
