### PR TITLE
fixed swappend prediction and label in example in documentation

### LINKED ISSUE #1859: Documentation: Focal loss example misleading
In the example of the focal loss (`tfa.losses.SigmoidFocalCrossEntropy`) the label and the prediction data seems to be swapped. 
This is misleading as `sigmoid_focal_crossentropy()` expects `y_true, y_pred`, whereas the example presents `y_pred, y_true`.

https://github.com/tensorflow/addons/blob/efa0cd9c86578f53a2eb9d80849e186bffa4d64a/tensorflow_addons/losses/focal_loss.py#L42-L47

https://github.com/tensorflow/addons/blob/efa0cd9c86578f53a2eb9d80849e186bffa4d64a/tensorflow_addons/losses/focal_loss.py#L90-L92

### PR DESCRIPTION
**Pull request by ketograph**
Swapped the label and the network output in a documentation example.

Fixes #1859

### CODE REVIEW

**Comment by ketograph** [comment]
I don't have a Google account, is there a way to sign the CLA nonetheless?

**Comment by autoih** [comment]
Thanks @ketograph, [here](https://cla.developers.google.com/about) is about CLA.

**Comment by autoih** [comment]
Thanks for the contribution, @ketograph. Please take a look [here](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#contributor-license-agreement) and [here](https://cla.developers.google.com/about).

**Comment by ketograph** [comment]
As I have no Google Account and don't want to register one, I cannot sign the CLA. If it is not possible to sign the CLA or otherwise pass the test, I would abort this pull request.

**Comment by seanpmorgan** [comment]
> As I have no Google Account and don't want to register one, I cannot sign the CLA. If it is not possible to sign the CLA or otherwise pass the test, I would abort this pull request.

Unfortunately it is a requirement. Thanks for bringing this up though we'll get it patched!

**Pull request closed without merging**
