### PR TITLE
[WIP] One Cycle LR implementation

### PR DESCRIPTION
**Pull request by joaogui1**
Pretty much a copy of [titu1994's implementation](https://github.com/titu1994/keras-one-cycle/blob/master/clr.py), the biggest difference being that I use the optmizer's learning rate as max learning rate, instead of letting the user define it in the callback constructor
Solves #317

### CODE REVIEW

**Comment by joaogui1** [comment]
Hey, what exactly am I supposed to test? I don't have much experience in that area, sorry

**Comment by Gokkulnath** [comment]
@joaogui1 I was initially working on it but couldn't complete because of some other engagements. You can refer  https://github.com/tensorflow/addons/issues/61#issuecomment-501815593  for more details.

I will add some tests if possible sometime later this week.

**Comment by joaogui1** [comment]
Thanks, I will take a look at the LearningRateScheduler tests and see if I can make some tests for OneCycleLR today

**Comment by joaogui1** [comment]
I wrote two quick tests, but I seem to be getting an error when running in graph mode, specifically the 
`K.set_value(self.model.optimizer.lr, self._compute_lr())`
line throws an error.
Did you experience something similiar @Gokkulnath ?

**Comment by seanpmorgan** [comment]
> I wrote two quick tests, but I seem to be getting an error when running in graph mode, specifically the
> `K.set_value(self.model.optimizer.lr, self._compute_lr())`
> line throws an error.
> Did you experience something similiar @Gokkulnath ?

Hi @joaogui1 could you try using the _set_hyper like self.model.optimizer._set_hyper('learning_rate', lr)

**Comment by joaogui1** [comment]
> > I wrote two quick tests, but I seem to be getting an error when running in graph mode, specifically the
> > `K.set_value(self.model.optimizer.lr, self._compute_lr())`
> > line throws an error.
> > Did you experience something similiar @Gokkulnath ?
> 
> Hi @joaogui1 could you try using the _set_hyper like `self.model.optimizer._set_hyper('learning_rate', lr)`

Hi, I tried that and now I keep getting:
`FailedPreconditionError: Error while reading resource variable training/SGD/learning_rate from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/training/SGD/learning_rate)
	 [[node ReadVariableOp (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]]`

**Comment by seanpmorgan** [comment]
@joaogui1 Sorry for the delay. As you said that error is likely because you're testing in Graph and Eager and the way the variables are created they have no yet been initialized.

Could you look at the way https://github.com/tensorflow/addons/pull/644/files implements test cases as an example.

**Comment by joaogui1** [comment]
Hi, thanks for the help! I will be spending next week on khipu.ai, so I will resume working on this pull request the week after that

**Pull request closed without merging**
