### PR TITLE
Improve version check variable names

### PR DESCRIPTION
**Pull request by seanpmorgan**
# Description

Small improvement on the variable names. Previously it was difficult to know that MAX_VERISON was not included.

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [x] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Do we think we need to store the old variable name?
`MAX_TF_VERSION = EXCLUSIVE_MAX_TF_VERSION = "2.5.0"`

I haven't seen anyone utilize these variables outside of Addons, and we are on 0.x release but it is possible others are using these.

**Comment by WindQAQ** [comment]
> Do we think we need to store the old variable name?
> e.g. `MAX_TF_VERSION = EXCLUSIVE_MAX_TF_VERSION = "2.5.0"`
> 
> I haven't seen anyone utilize these variables outside of Addons, and we are on 0.x release but it is possible others are using these.

I don't think we should. Users should afford the consequence of using non-public API. I am thinking to prefix those variables with `_`. Though there is nothing really private in Python, it should be enough to tell users that one shouldn't use those stuff.

**Comment by seanpmorgan** [comment]
> > Do we think we need to store the old variable name?
> > e.g. `MAX_TF_VERSION = EXCLUSIVE_MAX_TF_VERSION = "2.5.0"`
> > I haven't seen anyone utilize these variables outside of Addons, and we are on 0.x release but it is possible others are using these.
> 
> I don't think we should. Users should afford the consequence of using non-public API. I am thinking to prefix those variables with `_`. Though there is nothing really private in Python, it should be enough to tell users that one shouldn't use those stuff.

Generally agree with all above, but since we import these into a different modules (e.g. `ensure_tf_install`) maybe we should just keep them as global syntax as done in this pr?

**Comment by WindQAQ** [comment]
> Generally agree with all above, but since we import these into a different modules (e.g. `ensure_tf_install`) maybe we should just keep them as global syntax as done in this pr?

Looks good to me :-)

**Review by WindQAQ — APPROVED** [review]

**Pull request merged**
