### PR TITLE
Update optimizers for doctest on the docstring.

### LINKED ISSUE #2066: Testable docstrings
https://github.com/tensorflow/addons/pull/677 is merged, so we are happy to introduce doctest on the docstring. This feature is awesome that can avoid wrong example usage.

Because the change might be small, please submit one sub-module, for example, activations, per PR. For more details, please refer to https://www.tensorflow.org/community/contribute/docs_ref.

Note that available namespace in our repo is `tf` for `tensorflow`, `np` for `numpy` and `tfa` for `tensorflow_addons`.

- [x] activations: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations
- [ ] callbacks: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/callback
- [ ] image: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/image
- [x] layers: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/layers
- [x] losses: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/losses
- [x] metrics: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/metrics
- [ ] optimizers: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/optimizers
- [x] rnn: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/rnn
- [ ] seq2seq: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq
- [ ] text: https://github.com/tensorflow/addons/tree/master/tensorflow_addons/text

It's also really appreciated that one can help improve our doc based on https://www.tensorflow.org/community/contribute/docs_style when scrutinizing docstrings.

### PR DESCRIPTION
**Pull request by ashwin-phadke**
# Description

Part of #2066.

## Type of change

- [X]  Updated or additional documentation

# Checklist:

- [X] This PR addresses an already submitted issue for TensorFlow Addons
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ashwin-phadke** [comment]
The flake8 linting errors appears to be of the kind `line too long` , most of the other errors were fixed. What could be the solution for line too long?

**Comment by WindQAQ** [comment]
> The flake8 linting errors appears to be of the kind `line too long` , most of the other errors were fixed. What could be the solution for line too long?

Hi, have you tried `python -m black .`?

**Comment by ashwin-phadke** [comment]
> > The flake8 linting errors appears to be of the kind `line too long` , most of the other errors were fixed. What could be the solution for line too long?
> 
> Hi, have you tried `python -m black .`?

I will try and check if that works
[Update to be posted here ]  -

**Comment by ashwin-phadke** [comment]
> Thanks for the contribution! I think we should standardize the variable naming. Can we change the variable name `opt` to `optimizer` for consistency?

Yes it appears that some scripts have `opt` and some `optimizer`, , I'll change it to `optimizer` for better readability as mentioned.

**Comment by ashwin-phadke** [comment]
@WindQAQ  can you help me out figuring out why so many tests are not going through despite me only fixing linting issues, previous runs seemed to be successful.

**Comment by Harsh188** [comment]
Hey @ashwin-phadke, looks like you are having trouble with not just formatting issues but also some of your python doctests are failing. First, let's get those formatting issues out by doing the following steps:
1.  Read up on https://www.tensorflow.org/community/contribute/code_style and use `pylint` with the custom TensorFlow style to debug your formatting issues.
2.  Check out https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style and utilize the pre-commit hook.
3. Make sure you are running `python -m black ./` and `python -m flake8` pre-commit.

Now to solve your doctest issues, use `pytest -v --doctest-modules` and debug the errors. More information on `pytest` can be found here https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#code-testing

Hope this helps :)

**Comment by Harsh188** [comment]
@ashwin-phadke any progress on this?

**Comment by ashwin-phadke** [comment]
> @ashwin-phadke any progress on this?

I do not know Docker so cannot run pre-commit hooks, any other options to this?

**Comment by AakashKumarNain** [comment]
Closing this as there has been no recent activity. Please reopen again the changes still apply

**Pull request closed without merging**
