### PR TITLE
Made blur faster by using gaussian decomposition property.

### PR DESCRIPTION
**Pull request by jrruijli**
# Description

Image blurring is now linear in kernel size instead of quadratic by making use of decomposition of Gaussian.
For large kernels this results in especially large speed-ups.

## Type of change

More efficient implementation of gaussian_filter2d.
(Note that mean_filter2d could also be implemented with two 1d filters).

# Checklist:

- [X] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)

# How Has This Been Tested?
Using standard testing. The original (unmodified) test still works:

python3 -m pytest tensorflow_addons/image/tests/filters_test.py 
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: ~/home/jrru/git_repositories/addons_mine, inifile: pytest.ini
plugins: extra-durations-0.1.3, xdist-1.34.0, forked-1.3.0, typeguard-2.10.0
collected 116 items                                                                                

tensorflow_addons/image/tests/filters_test.py .............................................. [ 39%]
......................................................................                       [100%]

==================================== sum of all tests durations ====================================
11.08s
======================================= 116 passed in 11.19s =======================================

### CODE REVIEW

**Comment by jrruijli** [comment]
@googlebot I fixed it.

**Comment by bhack** [comment]
Check https://github.com/tensorflow/addons/pull/1450 and more general  https://github.com/tensorflow/tensorflow/issues/39050

**Comment by jrruijli** [comment]
@googlebot I fixed it.

**Comment by ghosalsattam** [comment]
I guess running  2D in Convolution in-stead of 2 1D convolutions takes lesser time in GPU due to parallel computations. So, earlier I left it as 2D convolutions only.

**Comment by jrruijli** [comment]
@googlebot I fixed it.

**Comment by jrruijli** [comment]
"I guess running 2D in Convolution in-stead of 2 1D convolutions takes lesser time in GPU due to parallel computations. So, earlier I left it as 2D convolutions only."

The main problem is that the 2D convolution is quadratic in the kernel size. Earlier, I used a Gaussian blur with a sigma of 3, for which a proper kernel is 17x17 (around 3 sigma). The difference is doing 1 convolution with 298 values or two convolutions with 17 values. Parallelism will not help much here.

**Comment by bhack** [comment]
Please check both refence tickets that I've mentioned in the previous comment.

**Comment by jrruijli** [comment]
Did I close this? I was having trouble with git...

Anyway, according to some local testing, for small kernels (<3) the separable version is about 20% slower than the 2D version. Note that blurring generally requires a bit larger kernels (you want a kernel of 7 for a sigma of 1). For larger kernels (> 15), the separable version is about twice as fast.

On CPU, for small kernels the differences are negligible. For a kernel of size 10 the separable version is almost 5x faster.

On TPUs I don't know what will happen.

So let me know if this worthwhile or you prefer waiting until the depthwise convolution gets updated to support separable kernels.

**Pull request closed without merging**
