### PR TITLE
Update version.py

### PR DESCRIPTION
**Pull request by seanpmorgan**
# Description

Preparing for 0.13 release

### CODE REVIEW

**Comment by seanpmorgan** [comment]
I'm not sure we're this Kokoro `[11:11:49][ERROR] Config validation failed!` is coming from. I'm leaning toward server side issue since it passed on the TF2.5 PR yesterday and there hasn't been any changes that should be causing this.

**Comment by bhack** [comment]
Now it is failed but empty.

**Comment by bhack** [comment]
Ok it was not related to the single/double quote pattern (as we have in other Tensorflow repos). if you want you can revert to https://github.com/tensorflow/addons/pull/2478/commits/c21c18729ca1596a7ba5936cc943789cdad132e5

**Comment by seanpmorgan** [comment]
> Ok it was not related to the single/double quote pattern (as we have in other Tensorflow repos). if you want you can revert to [c21c187](https://github.com/tensorflow/addons/commit/c21c18729ca1596a7ba5936cc943789cdad132e5)

Thanks for trying. Yeah lets just revert to minimize the diff. We can force merge since I think kokoro is just malfunctioning

**Pull request merged**
