### PR TITLE
Revert WeightNorm mutex

### PR DESCRIPTION
**Pull request by seanpmorgan**
* Revert b62bbde

See https://github.com/tensorflow/addons/pull/1025 for more details

### CODE REVIEW

**Comment by Squadrick** [comment]
But the tests seem to be failing for Ubuntu, re-triggering. Might be that the tests are flaky.

**Comment by seanpmorgan** [comment]
Yeah not sure what is happening with the test cases here. I was going to comb over the history of the test file to see what changes were made since this, but haven' t had the time yet.

**Comment by Squadrick** [comment]
@seanpmorgan I'll take a look. It's mostly due to a change I authored that introduced `.remove`. It's quite annoying because I can't repro on my local system (mac), but it seems to be failing for Ubuntu.

**Comment by fsx950223** [comment]
> Block merge until failing tests are resolved, and RCA'd.

Layers have same kernel, why not compare kernel directly?

**Comment by gabrieldemarmiesse** [comment]
@googlebot I consent

**Comment by gabrieldemarmiesse** [comment]
I've merged master into your branch to update it and fixed any formatting/conflicts it might have. If you need to do some more modifications, please do `git pull` beforehand.

**Pull request closed without merging**
