### PR TITLE
Update tensorflow==2.0.0b1 requirement

### PR DESCRIPTION
**Pull request by mels630**
* Fix requirements.txt
* Update README.md to correct package version name
* Necessary to bazel build addons package

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Hi @mels630 ! Thanks for your contribution! Sorry if it's not clear in the documentation please let us know where we can improve, but:

1. `tensorflow==2.0.0-beta1` should be an equivalent pip package to `tensorflow==2.0.0-b1` ... we just used the name in the webpage: https://www.tensorflow.org/beta
2. Our master branch is built against tf2-nightly. Though you can see on our v0.4 branch it is correctly pinned to tf2-beta: https://github.com/tensorflow/addons/blob/r0.4/requirements.txt

**Comment by seanpmorgan** [comment]
Closing this PR.. but feel free to continue discussion about what you found confusing or if you have any suggestions for change. Welcome to Addons!

**Comment by mels630** [comment]
Thanks for the quick feedback, Sean.

1. I didn't realize that tensorflow==2.0.0-beta1 is equivalent to
tensorflow==2.0.0-b1, so I agree that no change needed there.
2. Is tf2-nightly a pip-installable package? The use case that lead me to
the change was that I tried to bazel-build the tf-addons package from git
source after pip installing tensorflow==2.0.0-b1, then the ./configure.sh
script failed at the pip install -r requirements.txt. Note that I wasn't
building within the suggested docker container, so this could be on me; but
it wasn't clear that I shouldn't be able to bazel build in this fashion.

Thanks!
Matt

**Comment by seanpmorgan** [comment]
Hi Matt,

1. Yeah it's a bit confusing... should be cleaned up once we get a release candidate in the near future.
2. We recommend you use the docker container but it isn't required (especially if for example you'd like to build for macos). The `./configure.sh` script will automatically download the requirements... for master branch that is `tf-nightly-2.0-preview` while on the r0.4 branch that is `tensorflow==2.0.0b1`

**Comment by mels630** [comment]
Hi Sean,

> The ./configure.sh script will automatically download the requirements...
for master branch that is tf-nightly-2.0-preview

So this is my concern -- in my experience, running the configure.sh script
(without the docker container) failed at the bit where it tries to pip
install -r requirements.txt:

# tf_addons (master)$ ./configure.sh
Tensorflow will be upgraded to 2.0. Are You Sure? [Y/n] Y
Installing...
Collecting tf-nightly-2.0-preview (from -r requirements.txt (line 1))
   ERROR: Could not find a version that satisfies the requirement
tf-nightly-2.0-preview (from -r requirements.txt (line 1)) (from versions:
none)
ERROR: No matching distribution found for tf-nightly-2.0-preview (from -r
requirements.txt (line 1))

Perhaps user error is the issue, but I can't see how -- I tried to pip
install this from the command line as well and got the same error.

Thanks,
Matt

**Comment by seanpmorgan** [comment]
Ah it looks like they only publish linux wheels:
https://pypi.org/project/tf-nightly-2.0-preview/2.0.0.dev20190615/#files

Can you confirm your OS and python version?

**Comment by mels630** [comment]
Aha, that's it. I'm running on Mac (mac OS Sierra 10.12.6) and Python 3.7.2

(tf2.0.0b1) L(24-1:1146) melsey@LPA-MELS-MBPT Projects $ python --version
Python 3.7.2
(tf2.0.0b1) L(24-1:1155) melsey@LPA-MELS-MBPT Projects $ uname -a
Darwin LPA-MELS-MBPT.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct 10
20:06:00 PDT 2018; root:xnu-3789.73.24~1/RELEASE_X86_64 x86_64

**Comment by seanpmorgan** [comment]
Do I looked into this a little more because we have nightly macos builds that are successful. It seems the macos packaging might just be broken for a few days:
https://pypi.org/project/tf-nightly-2.0-preview/2.0.0.dev20190614/#files

Shows last week a py36 macos wheel being published.

**Comment by mels630** [comment]
Thanks for tracking the issue down, Sean. I will keep an eye out for that
to be fixed.

Unrelated: Are you still looking for a maintainer for tfa.image.transform_ops?
I could take that on, though I'm not entirely clear on what the immediate
tasks are beyond updating the maintainers list. I would also take
tfa.image.distance_transform_ops if needed, though it's less clear to me
what exactly that bit of code is doing at first glance.

Best,
Matt

**Comment by seanpmorgan** [comment]
Hi Matt,

Addons is always looking for new maintainers. There may be no immediate task -- but any code reviews for your submodule (or other submodules) are greatly appreciated. A lot of things ported from contrib may have bugs or TODOs as well so thorough review and maintenance is always appreciated.

See @WindQAQ's current PR: 
https://github.com/tensorflow/addons/pull/299

**Pull request closed without merging**
