### PR TITLE
WIP: fix flaky filter test

### PR DESCRIPTION
**Pull request by WindQAQ**
Addresses #801.

### CODE REVIEW

**Comment by WindQAQ** [comment]
I suppose it's due to precision but not so sure about it.

Please do not merge it at this moment. Let's test it multiple times on CI :P

**Comment by WindQAQ** [comment]
Another known issue is that `atomicAdd` on GPU may cause non-deterministic behavior. The repo under NVIDIA gives the detailed descriptions/discussions.

https://github.com/NVIDIA/tensorflow-determinism
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/depthwise_conv_op_gpu.h

**Comment by seanpmorgan** [comment]
> I suppose it's due to precision but not so sure about it.
> 
> Please do not merge it at this moment.

Just a note, WIP in title will prevent merging now.

**Comment by Squadrick** [comment]
@WindQAQ Is this good to go? Maybe pull from upstream master to update to the newer GitHub actions to test for flaky-ness?

**Comment by gabrieldemarmiesse** [comment]
@googlebot  I consent

**Comment by gabrieldemarmiesse** [comment]
I've merged master into your branch to update it and fixed any formatting/conflicts it might have. If you need to do some more modifications, please do git pull beforehand.

**Comment by gabrieldemarmiesse** [comment]
This pull request has been left without updates for a while now. I'll be closing it. If there are changes, feel free to re-open.

**Pull request closed without merging**
