### PR TITLE
beam search decoding procedure added to seq2seq_nmt tutorial

### PR DESCRIPTION
**Pull request by abhishek-niranjan**
# Description
Beam-Search tutorial for NMT. [Link to colab notebook](https://colab.research.google.com/drive/1YFsjenxCDqlBj9Qe0mq-w-Wq-E1ZIQkf?usp=sharing)

Brief Description of the PR:
Added the steps to use [`tfa.seq2seq.BeamSearchDecoder`](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/BeamSearchDecoder) during inference and output beam results with their scores.

Fixes # (issue)
#1915 

## Type of change

- [ ] Bug fix
- [x] New Tutorial
- [x] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Activation and the changes conform to the [activation contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md#contribution-guidelines)
- [ ] New Callback and the changes conform to the [callback contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/README.md#contribution-guidelines)
- [ ] New Image addition and the changes conform to the [image op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md#contribution-guidelines)
- [ ] New Layer and the changes conform to the [layer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/README.md#contribution-guidelines)
- [ ] New Loss and the changes conform to the [loss contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/README.md#contribution-guidelines)
- [ ] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)
- [ ] New Optimizer and the changes conform to the [optimizer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/README.md#contribution-guidelines)
- [ ] New RNN Cell and the changes conform to the [rnn contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/README.md#contribution-guidelines)
- [ ] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [ ] New Text addition and the changes conform to the [text op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/README.md#contribution-guidelines)

# Checklist:

- [ ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [x] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?
Not adding a new feature or any bugfix as such. Modified the seq2seq NMT tutorial notebook to explain how to use `tfa.seq2seq.BeamSearchDecoder` during inference step. The encoder and decoder stack defined in notebooks are verified to output correct dimensions in the notebook itself.

### CODE REVIEW

**Comment by guillaumekln** [comment]
@w4nderlust Could you look if this addresses your main points from https://github.com/tensorflow/addons/issues/1915?

**Comment by w4nderlust** [comment]
It looks good to me. I have a question though, but it's more related with how BeamSearch actually works in TF2 than the tutorial itself.
Not sure if relevant, but asking it here as it may help improve the tutorial too.

My understanding of beam search is that at each step, for each beam (pair of sequence and score), you sum the log likelihood of each prediction coming from the model to the beam, concatenate the prediction to the sequence in the beam, sort the beams by log likelihood to keep the top k and then repeat.

Here what is not clear to me is what actually are the outputs of the BeamSearch. Here you keep concatenating the K ids returned at each step, but I'm not sure if the user should keep track of the beam themselves or what, because if I have my top 3 beams at one step that are the sequences [a], [b] and [c], then the top 3 beams at the next step could be [b,b], [b,c], [a,a], so if I understand correctly the step function would return b, c, a, but those, concatenated with the previous top 3 beams, will lead to [a,b] [b,c] and [c,a], which are not the actual high log likelihood sequences.
I guess some further clarification about this to remove doubts either here or in the docs themselves would be great.

**Comment by abhishek-niranjan** [comment]
@w4nderlust 

> Here what is not clear to me is what actually are the outputs of the BeamSearch. Here you keep concatenating the K ids returned at each step, but I'm not sure if the user should keep track of the beam themselves or what, because if I have my top 3 beams at one step that are the sequences [a], [b] and [c], then the top 3 beams at the next step could be [b,b], [b,c], [a,a], so if I understand correctly the step function would return b, c, a, but those, concatenated with the previous top 3 beams, will lead to [a,b] [b,c] and [c,a], which are not the actual high log-likelihood sequences.

Yes, you are correct about this. The way it was written in the notebook was indeed the greedy sampling technique. Apologies for that. I went through the source to find out how to call `beam_search_step()` function in the case of `BeamSearchDecoder`. As it turns out that there is no need to call `BasicDecoder.step() or BeamSearchDecoder.step()` function explicitly. The [`dynamic_decode()`](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/dynamic_decode) calls `initialize()` once and `step()` repeatedly on the Decoder object and user doesn't need to keep track of anything. 
The correct way to implement these Decoders are explained [here](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq) (Although not entirely correct), So I followed these steps rather than what's in the official [tutorial](https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt) now. I have updated the colab notebook with correct implementation and committed the new changes. 

Also, I'd like to update the Decoder(Basic and BeamSearch) usage instructions [here](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq). Should I go ahead?  Besides, when I was going through the source and the API documentation of `tfa.seq2seq`, I realized that some of the functions/classes could be explained better. I'd like to contribute to that as well.

**Comment by abhishek-niranjan** [comment]
@guillaumekln commenting for visibility.

**Comment by w4nderlust** [comment]
Thank you @abhishek-niranjan for the clarification and the improvement! If it could be useful, here's what we do in Ludwig with beam and greedy decoders, which is very similar to your new implementation: https://github.com/uber/ludwig/blob/master/ludwig/decoders/sequence_decoders.py#L342-L522

**Comment by abhishek-niranjan** [comment]
@w4nderlust concisely written. I wish I had known about this when I was creating the tutorial. :P

**Comment by w4nderlust** [comment]
Right : We are currently work on it, last commit was less than a week ago :)

**Comment by abhishek-niranjan** [comment]
@guillaumekln can you check the tutorial once and suggest any changes that you feel should be added. In the meantime, I was hoping I could update the instructions for `BasicDecoder` and `BeamSearchDecoder` [here](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq) if that's fine.

**Comment by w4nderlust** [comment]
@abhishek-niranjan FYI we anded up doing some changes in before merging that PR which include a mechanism for reconstructing the probabilities for each step of the generated sequence (for the purpose of computing the loss and perplexity at eval time). Check it out and feel free to grab pieces of code if you need. https://github.com/uber/ludwig/blob/master/ludwig/decoders/sequence_decoders.py

**Comment by guillaumekln** [comment]
@abhishek-niranjan Thanks! The tutorial is improved so I think we can merge this. Can you resolve the conflicts?

> In the meantime, I was hoping I could update the instructions for BasicDecoder and BeamSearchDecoder here if that's fine.

Sure. You can do that in a separate PR.

**Comment by abhishek-niranjan** [comment]
@guillaumekln I've resolved the conflicts. 
> Sure. You can do that in a separate PR.

Thanks, I'll start on that right away.


@w4nderlust Thanks for sharing the code, definitely a help when you need to calculate perplexity. I'll see if I could add this to the tutorial in the future. BTW, thanks for introducing me to Ludwig. Great project!

**Comment by w4nderlust** [comment]
> @w4nderlust Thanks for sharing the code, definitely a help when you need to calculate perplexity. I'll see if I could add this to the tutorial in the future. BTW, thanks for introducing me to Ludwig. Great project!

You are welcome! Yes that function to reconstruct probabilities is used in Ludwig to then calculate eval loss and perplexity (you can find those too in modules/metrics and losses if you need).

**Review by guillaumekln — APPROVED** [review]

**Comment by abhishek-niranjan** [comment]
@guillaumekln The https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt is still showing the old tutorial. Is this normal?

**Comment by guillaumekln** [comment]
As far as I know the documentation is not automatically updated. We should wait for the next synchronization. @seanpmorgan Is that correct?

**Comment by seanpmorgan** [comment]
> As far as I know the documentation is not automatically updated. We should wait for the next synchronization. @seanpmorgan Is that correct?

Yes we have to get TF docs team to update the site. We'll likely make a patch release and docs update after this is merged with some other reorganization: https://github.com/tensorflow/addons/pull/2162

**Pull request merged**
