### PR TITLE
fix float16 and float64 kernels

### PR DESCRIPTION
**Pull request by fsx950223**
# Description

Brief Description of the PR:
Fix edt float16 and float64 kernels
Fixes # (issue)

## Type of change

- [ ] Bug fix
- [ ] New Tutorial
- [ ] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Activation and the changes conform to the [activation contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md#contribution-guidelines)
- [ ] New Callback and the changes conform to the [callback contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/README.md#contribution-guidelines)
- [ ] New Image addition and the changes conform to the [image op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md#contribution-guidelines)
- [ ] New Layer and the changes conform to the [layer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/README.md#contribution-guidelines)
- [ ] New Loss and the changes conform to the [loss contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/README.md#contribution-guidelines)
- [ ] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)
- [ ] New Optimizer and the changes conform to the [optimizer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/README.md#contribution-guidelines)
- [ ] New RNN Cell and the changes conform to the [rnn contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/README.md#contribution-guidelines)
- [ ] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [ ] New Text addition and the changes conform to the [text op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/README.md#contribution-guidelines)

# Checklist:

- [ ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
*

### CODE REVIEW

**Review by WindQAQ — COMMENTED** [review]
Can you explain why this can solve the issue?

**Comment by fsx950223** [comment]
> Can you explain why this can solve the issue?

I don't know why float16 and float64 kernels crashed with same setting as tf.float32, but reduce block_dim solves the bug.

**Comment by WindQAQ** [comment]
I guess this will generate wrong results when the original threads per block is larger than 256?

**Comment by fsx950223** [comment]
> I guess this will generate wrong results when the original threads per block is larger than 256?

No, it's a resource exceed bug.

**Comment by WindQAQ** [comment]
> > I guess this will generate wrong results when the original threads per block is larger than 256?
> 
> No, it's a resource exceed bug.

Hmm, if I understand correctly, the implementation is one thread do one plane (h*w) EDT. So if block_count == 1024 and  thread_per_block == 512 (which means batch*channel == 2**19), this change will launch instead 2**18 threads, and some image planes are not going to be updated, right?

**Comment by fsx950223** [comment]
> > > I guess this will generate wrong results when the original threads per block is larger than 256?
> > 
> > 
> > No, it's a resource exceed bug.
> 
> Hmm, if I understand correctly, the implementation is one thread do one plane (h, w) EDT. So if block_count == 1024 and thread_per_block == 512 (which means batch \times channel == 2^19), this change will launch 2^18 threads instead, and some image planes are not going to be updated, right?

The results are same as before, but inference may a little slower.

**Comment by WindQAQ** [comment]
Can you add a test of batch x channels == 2048 or larger?

**Comment by fsx950223** [comment]
> > > > I guess this will generate wrong results when the original threads per block is larger than 256?
> > > 
> > > 
> > > No, it's a resource exceed bug.
> > 
> > 
> > Hmm, if I understand correctly, the implementation is one thread do one plane (h, w) EDT. So if block_count == 1024 and thread_per_block == 512 (which means batch \times channel == 2^19), this change will launch 2^18 threads instead, and some image planes are not going to be updated, right?
> 
> The results are same as before, but inference may a little slower.



> Can you add a test of batch x channels == 2048 or larger?

Good point, I try it.

**Comment by fsx950223** [comment]
> Can you add a test of batch x channels == 2048 or larger?

I found I should set block_count*4 and set thread_per_block/4

**Comment by WindQAQ** [comment]
Can you try this?

https://github.com/tensorflow/tensorflow/blob/100c0d6538986797e1b29877b9cbbc687ba54853/tensorflow/core/util/gpu_launch_config.h#L156-L159

**Comment by fsx950223** [comment]
> Can you try this?
> 
> https://github.com/tensorflow/tensorflow/blob/100c0d6538986797e1b29877b9cbbc687ba54853/tensorflow/core/util/gpu_launch_config.h#L156-L159

Good, thanks.

**Review by WindQAQ — APPROVED** [review]

**Pull request merged**
