### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by failure-to-thrive**
#854

### CODE REVIEW

**Comment by failure-to-thrive** [comment]
@googlebot I signed it!

**Comment by seanpmorgan** [comment]
@failure-to-thrive Thanks very much for the contribution! We'll want to remove `configure.sh` and replace calls:
https://github.com/tensorflow/addons/search?q=configure.sh&unscoped_q=configure.sh

Also lint is failing.. Could you please try `black configure.py`. We're in the middle of a transition and soon this can be called using the standard cmake commands. (Or [prehooks](https://github.com/tensorflow/addons/pull/943))

**Comment by failure-to-thrive** [comment]
Sorry for the delay. First, report from the `CI / flake8` differs from my own local (non docker). Where is a ground-truth? Second, after running the `black` there are still some errors. Of course I can fix them manually, but I'm not sure it will pass the test of `CI / flake8` and whether I should fix them at all. I'm a little bit confused.

**Comment by seanpmorgan** [comment]
@failure-to-thrive Sorry for you being a bit of a guinea pig while we transition our code style. Could you please push to the commit which ran `black` so we can see where the disagreements between flake8 and black are occuring.

**Comment by gabrieldemarmiesse** [comment]
I would recommend that you merge master into your branch. It's going to be a lot easier to help you afterwards :)

**Comment by seanpmorgan** [comment]
> I would recommend that you merge master into your branch. It's going to be a lot easier to help you afterwards :)

Yes great point. Merging master may resolve the discrepancies your seeing on local vs CI

**Comment by seanpmorgan** [comment]
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Faddons%2Fpull%2F939) for more info**.

Don't worry about this. I can override the CLA check. There is an issue with CLA bot and multiple contributors

**Comment by gabrieldemarmiesse** [comment]
@googlebot I consent

**Comment by gabrieldemarmiesse** [comment]
@failure-to-thrive  I did the necessary. Please just do `git pull` and you'll be good to go :)

**Comment by failure-to-thrive** [comment]
> Could you please push to the commit which ran `black` so we can see where the disagreements between flake8 and black are occuring.

Those disagreements are:
```
configure.py:35:1: E302 expected 2 blank lines, found 1
configure.py:133:1: E402 module level import not at top of file
configure.py:136:1: E402 module level import not at top of file
```
Now @gabrieldemarmiesse has fixed them manually(?).

**Comment by gabrieldemarmiesse** [comment]
I fixed them :) everything is working now

**Comment by failure-to-thrive** [comment]
> I fixed them :) everything is working now

That's great! But, please clarify has it been done manually or with an automated tool (or a special config)? It's important personally for me to further understand the workflow of this project, to understand what kind of magic was behind the scene because personally I stirive to avoid any modifications after automated tools.

**Comment by gabrieldemarmiesse** [comment]
Some stuff is done in an automated way, some other manually. Install the pre-commit and it will guide you. See https://github.com/tensorflow/addons/blob/master/STYLE_GUIDE.md#python

**Pull request merged**
