### PR TITLE
Add support for ARM architecture build from source

### PR DESCRIPTION
**Pull request by seanpmorgan**
# Description

Add support for building from source for ARM64 architectures. Requests for this can be seen in https://github.com/tensorflow/addons/issues/1982

## Type of change

- [x] Build improvement

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
- [x] This PR contains modifications to C++ custom-ops

### CODE REVIEW

**Comment by WindQAQ** [comment]
Is there any way to test arm build on CI?

**Comment by bhack** [comment]
https://github.com/tensorflow/build/issues/9

**Comment by bhack** [comment]
Also, if you want to track devcontainer/codespace for our images on this Arch please subscribe to https://github.com/microsoft/vscode-dev-containers/issues/558

**Comment by bhack** [comment]
/cc @bzhaoopenstack is there a way to add support for Addons CI/builds/wheels for ARM64 on your infra?

An alternative could be to use Qemu Github Action but it will be quite slow in emulation: https://github.com/uraimo/run-on-arch-action

**Review by WindQAQ — APPROVED** [review]
LGTM.

Thank you for the info @bhack! Seems that it's not an easy work. I prefer that we can work on it after this!

**Comment by seanpmorgan** [comment]
> LGTM.
> 
> Thank you for the info @bhack! Seems that it's not an easy work. I prefer that we can work on it after this!

Yeah we also have PowerPC builds enabled, but untested because of the same reason.

**Pull request merged**
