### PR TITLE
Sequence-to-Sequence NMT

### PR DESCRIPTION
**Pull request by Om-Pandey**
@seanpmorgan with reference to #335 , I have created the tutorial, please check and merge the files. Thanks!

### CODE REVIEW

**Comment by seanpmorgan** [comment]
@Om-Pandey Thanks very much for the contribution. Looks very good, but would it be possible to utilize a dataset found in tfds?
https://www.tensorflow.org/datasets/catalog/overview

Because our tutorials will be tested for correctness #485, we need these to run end-to-end.

**Comment by Om-Pandey** [comment]
@seanpmorgan yeah, I saw the datasets, I realize that I will have to change the entire data reading and cleaning process for them to conduct tokenization, even if I keep the model constant. Secondly, the translational datasets on https://www.tensorflow.org/datasets/catalog/overview are too large ≈ 1.5 GB each. I really don't have the kind of compute for it. 😅😬

But, I can assure you that the Dataset I used is pretty authentic([link](http://www.manythings.org/anki/deu-eng.zip)) and that my entire code has been tested on this so in case of testing for correctness there shouldn't be any errors. A link to the dataset has also been given in the notebook for reference. But, I can compile the cells again and re-upload along with results if you want, it will just make the notebook bigger though.

Check 'em:
t2
t1

**Comment by seanpmorgan** [comment]
> Removed a few of errors in display pipeline and removed unnecessary spaces

Thanks @Om-Pandey! So yeah having the results within the notebook is ideal for users to read through. You can remove the output from any cells that you don't think is necessary for understanding.

In order to run the code in Colab, you'll need to download the data. You can run commands on the colab host by prefixing with `!`. For example: `!wget --quiet https://dataset.tar.gz`

If the full notebook can run end-to-end then we can include this as a sort of "test" that the tf-docs team will run at each release.

How long is the total runtime of this example on a Colab instance?

**Comment by Om-Pandey** [comment]
@seanpmorgan yeah, so final changes have been made, I have added a lot of comments, which I think are sufficient for anyone to understand the code properly. As you said, I also coded-in the data downloading and unzipping processes on Colab, in my recent commit.
I just checked the notebook typically takes less than a minute to run, except the variable training time - but it typically takes 22secs per epoch, compute that by whatever number of epochs you find necessary to train. Finally, the testing and final prediction take about a minute too.

**Comment by John-8704** [comment]
@Om-Pandey Will you be implementing Attention Mechanism, Beam Search, Bi-directional encoder-decoder model? It's just that your notebook is not at all using TensorFlow Addons

**Pull request merged**
