### PR TITLE
Remove GELU

### LINKED ISSUE #2252: Drop GELU for 0.13 release
https://www.tensorflow.org/api_docs/python/tf/keras/activations/gelu will be available in TF2.4. Deprecation warning is already set for our upcming 0.12 release

### PR DESCRIPTION
**Pull request by aaronmondal**
Fixes #2252

As the above issue explains, GELU will be part of [`tf.keras.activations.gelu`](https://www.tensorflow.org/api_docs/python/tf/keras/activations/gelu).

### CODE REVIEW

**Comment by aaronmondal** [comment]
This should only be merged AFTER the 0.12 release.

**Review by AakashKumarNain — APPROVED** [review]

**Comment by AakashKumarNain** [comment]
LGTM. Thanks

**Comment by WindQAQ** [comment]
Should wait until 0.13 releases.

**Comment by seanpmorgan** [comment]
Thanks very much @aaronmondal! Sorry for not thinking this through, but following @WindQAQ suggestion in https://github.com/tensorflow/addons/issues/2252 would you mind refactoring this so that there is a version check and if >= TF2.4 it aliases tf.keras.activations.gelu and not remove this code for TF2.3?

We'll follow this PR up with a PR to remove GELU on the TFA v1.0 release

**Review by seanpmorgan — CHANGES_REQUESTED** [review]
Please keep this code for now and alias >= TF2.4

**Comment by aaronmondal** [comment]
Sure ill do that.

**Comment by aaronmondal** [comment]
Closing this since it is less cluttered to just send a new PR. See #2265 for the alias.

Cc: @seanpmorgan @WindQAQ @AakashKumarNain

**Pull request closed without merging**
