### PR TITLE
ADD CODEOWNER @marload

### PR DESCRIPTION
**Pull request by marload**
Hello, SIG-Addons!

I want to make continuous contributions including maintenance to the `tfa.metrics` Sub Pkg of `tfa`.

Thank You!

### CODE REVIEW

**Comment by marload** [comment]
Hello, @seanpmorgan !

I am sorry to mention!
Is there anything else I need to do other than add me to CODEOWNER if I want to be the maintainer?

Thank You!

**Comment by seanpmorgan** [comment]
> Hello, @seanpmorgan !
> 
> I am sorry to mention!
> Is there anything else I need to do other than add me to CODEOWNER if I want to be the maintainer?
> 
> Thank You!

No that is all. Thanks and happy to have you helping out!

**Comment by marload** [comment]
Thank you!


By the way, how can I get the authority to Merge?

**Comment by bhack** [comment]
We collect a little bit of contribution/ownership stats distributed over the time but probably @seanpmorgan can tell you something more about this informal policy.
E.g. You can start to take a look to your new ownership subdomain with the [metrics label](https://github.com/tensorflow/addons/labels/metrics)

**Comment by marload** [comment]
@bhack 

Thank You!
Then, can I be granted a write permission after additional continuous contributions?

**Comment by marload** [comment]
> Subpackage maintainership will only be granted after substantial contribution has been made in order to limit the number of users with write permission. Contributions can come in the form of issue closings, bug fixes, documentation, new code, or optimizing existing code. Submodule maintainership can be granted with a lower barrier for entry as this will not include write permissions to the repo.

Oh, the substantial contribution was talking about implementing new algorithms!

**Comment by seanpmorgan** [comment]
> > Subpackage maintainership will only be granted after substantial contribution has been made in order to limit the number of users with write permission. Contributions can come in the form of issue closings, bug fixes, documentation, new code, or optimizing existing code. Submodule maintainership can be granted with a lower barrier for entry as this will not include write permissions to the repo.
> 
> Oh, the substantial contribution was talking about implementing new algorithms!

Hi @marload! I've responded in the listserv but yeah substantial contributions don't have to be in the form of new contributions. Improving the repo in any manner is sufficient:
https://groups.google.com/u/2/a/tensorflow.org/g/addons/c/A-7mHct-3dY

**Pull request merged**
