### PR TITLE
kappa

### PR DESCRIPTION
**Pull request by jonpsy**
# Description

Brief Description of the PR:

Adds Kappa loss ipython notebook.  Hi, this is my first contribution to tensorflow addon. Constructive criticism is appreciated!

## Type of change

- [ ] Bug fix
- [x] New Tutorial
- [ ] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Activation and the changes conform to the [activation contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/README.md#contribution-guidelines)
- [ ] New Callback and the changes conform to the [callback contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/README.md#contribution-guidelines)
- [ ] New Image addition and the changes conform to the [image op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md#contribution-guidelines)
- [ ] New Layer and the changes conform to the [layer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/layers/README.md#contribution-guidelines)
- [ ] New Loss and the changes conform to the [loss contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/losses/README.md#contribution-guidelines)
- [ ] New Metric and the changes conform to the [metric contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/README.md#contribution-guidelines)
- [ ] New Optimizer and the changes conform to the [optimizer contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/README.md#contribution-guidelines)
- [ ] New RNN Cell and the changes conform to the [rnn contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/rnn/README.md#contribution-guidelines)
- [ ] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [ ] New Text addition and the changes conform to the [text op contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/README.md#contribution-guidelines)

# Checklist:

- [ ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
*

### CODE REVIEW

**Review by Harsh188 — COMMENTED** [review]
@jonpsy Thanks for contributing! Looks like you didn't clear out your notebook outputs. Could you please run the following lines of code to format the notebook.ipynb
```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs
$ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
```
Thanks

**Comment by jonpsy** [comment]
@Harsh188 hi, how do I setup the "Run in Google Colab" & "Download the jupyter notebook" button, I think the links would be available only after I merge?

**Comment by jonpsy** [comment]
Thanks for the help, how do I add the link for "Run in google colab", "Download notebook", "View on github" ?

**Comment by Harsh188** [comment]
Tensorflow.org: "https://www.tensorflow.org/addons/tutorials/kappa"
Google Colab: "https://colab.research.google.com/github/tensorflow/addons/blob/master/docs/tutorials/kappa.ipynb"
Github Source: "https://github.com/tensorflow/addons/blob/master/docs/tutorials/kappa.ipynb"
Download notebook: "https://storage.googleapis.com/tensorflow_docs/addons/docs/tutorials/kappa.ipynb"

Don't worry if the links don't exist at the moment. Once the PR gets merged I believe these links will become validated.

**Comment by jonpsy** [comment]
Done, thanks! Hopefully the tests should all pass! :)

**Comment by Harsh188** [comment]
@seanpmorgan @bhack Could you guys kindly take a look at this?

**Comment by wenmin-wu** [comment]
Yup @bhack, I'm still available as the code owner of Kappa Loss.

**Comment by bhack** [comment]
> Yup @bhack, I'm still available as the code owner of Kappa Loss.
> 

Can you review this PR?

**Comment by jonpsy** [comment]
Gentle nudge: @wenmin-wu

**Comment by jonpsy** [comment]
Closing this due to lack of activity.

**Comment by bhack** [comment]
@jonpsy Sorry but our Codeownership is a little bit broken. If you have any idea on how to improve the process please share your idea at https://github.com/tensorflow/addons/pull/2024 /cc @seanpmorgan

**Pull request closed without merging**
