### PR TITLE
Add a backport bot.

### LINKED ISSUE #1072: Have a bot backporting automatically bugfixes.
**Describe the feature and the current behavior/state.**

Currently we have to backport bugfixes by hand. This is fine now, but as the repository is growing, it'll become more and more painful.

**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where): no
- Is there already an implementation in another framework? (if so, where): yes (CPython, Ipython)
- Was it part of tf.contrib? (if so, where): no

**Which API type would this fall under (layer, metric, optimizer, etc.)**
no API
**Who will benefit with this feature?**
Maintainers who review PRs.

**Any other info.**

The tools we want exactly is this one: https://github.com/python/miss-islington
I don't know how hard it is to use it for tensorflow/addons. I have a bot if it can help: @bot-of-gabrieldemarmiesse 

CPython makes heavy use of this bot. I think it's a good idea to rely on it because we can expect them to maintain it for a very very long time to come.

Somebody needs to steal it!

or

If we could use a tool running with github actions that would be better though because we wouldn't need an instance running in the cloud to run the bot like they do (they use heroku). But we have to choose one which will open a pull request and not directly merge the bugfix. Some that I spotted:

https://github.com/qcastel/github-actions-backport
https://github.com/marketplace/actions/backport-bot
https://github.com/marketplace/actions/backporting
https://github.com/marketplace/actions/backport-commit

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
Fix #1072

@seanpmorgan I'll send you the BOT_TOKEN by email. You don't have to set the GITHUB_TOKEN . It's automatic.

You can look at the folks of https://github.com/qgis/QGIS who are making heavy use of this bot.

You need to add a label to the PR you want to backport: e.g. https://github.com/qgis/QGIS/pull/34436

See https://github.com/marketplace/actions/backport-bot

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
It seems we'll need to restart the tests after the secret has been added.

**Comment by seanpmorgan** [comment]
@gabrieldemarmiesse  `##[error]Input required and not supplied: bot_token`

Are we sure it should be a capitalized token?

**Comment by gabrieldemarmiesse** [comment]
Yes, because we get it with: ` ${{ secrets.BOT_TOKEN }}`

**Comment by seanpmorgan** [comment]
> Yes, because we get it with: ` ${{ secrets.BOT_TOKEN }}`

Gotcha I follow. Not sure what this issue is then. I've added the token:
image

**Comment by gabrieldemarmiesse** [comment]
I'm going to investigate.

**Comment by gabrieldemarmiesse** [comment]
From a security point of view, it would seem logical for it to work only when it's merged in master.

**Comment by gabrieldemarmiesse** [comment]
Ok I understand what is going on.
A secret can't be used in a pull request made by a fork. As such, we got the error. To fix it, we need to publicly expose the token, this is why they recommend to give it minimal permissions (actually less than a normal github user) to discourage people with bad intentions from using it. It's what I did.

I've put in the bio of my bot to report any issue to me. If I ever get a problem because someone wanted to prank me, I'll just remove the token and we'll drop the idea of automatic backporting. To check that the bot works, we'll need to test it with a pull request (we can close the pull request of the backport if it was just to test it).

This can be merged.

**Comment by gabrieldemarmiesse** [comment]
Actually no, github told me that my token has been revoked because it was found in a commit. Let me find how to fix that.

**Comment by gabrieldemarmiesse** [comment]
Ok if someone really wants to find my token it's possible, but this token has only comment rights and PR rights (but only in addons), so I suppose that it'd be in the best interest of this person to create another bot. I'm fine with the security implications of having this token out there.

This can be merged. Finally :p

**Pull request merged**
