### PR TITLE
Fix condition tracing in scale_channel

### PR DESCRIPTION
**Pull request by bhack**
Try to fix https://github.com/tensorflow/addons/issues/1829

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Thanks! Tracing the encapsulated function appears to work:
https://colab.research.google.com/drive/18QvTLJbS-21QD1tzNyP1G3gjq2SY4RjQ?usp=sharing

Would very much like the standardize the testing for tf.data.Dataset on tfa.image with #992

**Comment by bhack** [comment]
@seanpmorgan I don't know if in the original colab example, the one with `tf.function`,  there is a know tracing issue with `partial`.

**Comment by bhack** [comment]
I think that we have a more general issue here about `partial` with `@tf.function`.
Instead about `tf.data.Dataset` tests what is the plan with https://github.com/tensorflow/addons/issues/992?

**Comment by WindQAQ** [comment]
> I think that we have a more general issue here about `partial` with `@tf.function`.
> Instead about `tf.data.Dataset` tests what is the plan with #992?

Could you give me the link to the issue about `partial` and `tf.function`? Thank you!

**Comment by bhack** [comment]
@WindQAQ 

`fn = tf.function(partial(equalize_image, data_format=data_format))` 
it works.

```
@tf_function
def equalize(
```
doesn't trace `equalize_image` in partial

```
@tf_function
def equalize_image(
```
it works

**Comment by bhack** [comment]
We had some previous issues with `partial`:
https://github.com/tensorflow/tensorflow/issues/26091
https://github.com/tensorflow/tensorflow/issues/26602

But seems that they have not tested entering in `partial` with `@tf.function` like in your original colab.

**Comment by bhack** [comment]
If you are interested I am tying to check if `partial` inside a decorated function is a bug/limit of the tracer at https://github.com/tensorflow/tensorflow/pull/39541

**Pull request merged**
