### PR TITLE
[Do not merge] Testing CI build

### PR DESCRIPTION
**Pull request by karmel**

### CODE REVIEW

**Comment by karmel** [comment]
@seanpmorgan @av8ramit -- This appears to be working as intended. Tests pass currently; introducing an error results in failing tests and a failure log--

```
======================================================================
FAIL: test_transform_eager (__main__.ImageOpsTest)
test_transform_eager (__main__.ImageOpsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "/tmpfs/tmp/bazel/sandbox/linux-sandbox/15/execroot/__main__/bazel-out/k8-opt/bin/tensorflow_addons/image/transform_ops_test.runfiles/__main__/tensorflow_addons/image/python/transform_test.py", line 148, in test_transform_eager
    transform_ops.transform(image, [1] * 8))
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1013, in decorated
    return f(*args, **kwds)
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2235, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 896, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/tmpfs/src/github/tensorflow_addons/tf/local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([0]), array([0]))
not equal lhs = [5]
not equal rhs = [4.]
Mismatch: 25%
Max absolute difference: 1.
Max relative difference: 0.25
 x: array([[5, 4],
       [4, 4]])
 y: array([[4., 4.],
       [4., 4.]], dtype=float32)

----------------------------------------------------------------------
Ran 7 tests in 29.232s

FAILED (failures=1, skipped=1)
================================================================================
INFO: Elapsed time: 58.370s, Critical Path: 46.21s
INFO: 15 processes: 15 linux-sandbox.
INFO: Build completed, 1 test FAILED, 45 total actions
//tensorflow_addons/layers:layers_wrappers_py_test                       PASSED in 9.6s
//tensorflow_addons/layers:maxout_py_test                                PASSED in 3.8s
//tensorflow_addons/layers:poincare_py_test                              PASSED in 4.3s
//tensorflow_addons/losses:triplet_py_test                               PASSED in 6.0s
//tensorflow_addons/optimizers:lazy_adam_optimizer_test                  PASSED in 7.4s
//tensorflow_addons/text:text_ops_py_test                                PASSED in 1.5s
//tensorflow_addons/image:transform_ops_test                             FAILED in 30.4s
```
Those logs are not currently visible, but Amit is working on that.

@seanpmorgan - once the GPU test script is set up, we can run that as well.

**Comment by seanpmorgan** [comment]
Thanks again for the help! Couple of clarifying questions:

1. Can we run these nightly and on git hook?
1. Will we be able to display [build badges](https://source.cloud.google.com/results/invocations/215e3992-1c92-474a-8ae7-014e87ad8a18/targets) after test result are made public?

**Comment by karmel** [comment]
1) Yes, that is how they are setup now.
2) Yes, that is part of what @av8ramit is working on now. Turns out there may need to be some changes to the way the testing script is called, but he's working through that.

**Comment by seanpmorgan** [comment]
Closing as I'm not sure this is needed. Feel free to re-open if it is.

**Pull request closed without merging**
