### PR TITLE
Moved test out of run_all_in_graph_and_eager_mode in rrelu.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
See #1328

### CODE REVIEW

**Comment by fsx950223** [comment]
LGTM Thanks!

**Comment by AakashKumarNain** [comment]
@gabrieldemarmiesse Should I merge this or you want to make more changes?

**Comment by gabrieldemarmiesse** [comment]
you can merge this, thanks!

**Comment by AakashKumarNain** [comment]
Thank you.

**Pull request merged**
