### PR TITLE
bugfix: force WeightNormalization to execute in order

### PR DESCRIPTION
**Pull request by facaiy**
It seems that autograph is not smart enough, so we have to control execute order by ourselves.

### CODE REVIEW

**Comment by facaiy** [comment]
Following #453

**Comment by facaiy** [comment]
The new implementation still performs slightly better than the regression model (but worser than the precious implementation). I don't know what's wrong

https://colab.research.google.com/drive/1yXMehUQdFQ0mFtgJjYaj6FBCp8fr4Dt8#scrollTo=r66OUUrK_l_S

**Comment by facaiy** [comment]
I run it for five times, sometimes better, sometimes worser...

https://colab.research.google.com/drive/1yXMehUQdFQ0mFtgJjYaj6FBCp8fr4Dt8#scrollTo=UZd6V90eR4Gm

**Comment by seanpmorgan** [comment]
@facaiy I think it was for the wrong reason that it always outperformed using the previous  version (at least through one epoch). Could you try to increase the number of epochs a significant amount? Also mind making the colab sharable?

**Comment by facaiy** [comment]
sharable link: https://colab.research.google.com/drive/1yXMehUQdFQ0mFtgJjYaj6FBCp8fr4Dt8

**Pull request merged**
