### PR TITLE
BLD: Fix default GPU toolchain

### PR DESCRIPTION
**Pull request by seanpmorgan**
Fixes:
1) Currently building GPU package from source fails outside of the docker container. The default toolchain was the one using devtoolset-7 and is specific to that container. See https://github.com/tensorflow/addons/issues/445#issuecomment-524651126. Now the default GPU toolchain will find the include directories for the host compiler and CUDA install.
2) More recent bazel versions require `cc_toolchain` to utilize a `cc_toolchain_config`. It was already being used on the manylinux2010 toolchain: https://github.com/tensorflow/addons/blob/master/build_deps/toolchains/gcc7_manylinux2010-nvcc-cuda10.0/BUILD#L51

Cleans: 
1) Move all toolchains into a single directory
2) Remove some unnecessary toolchain configs that we do not support.

cc @lukaszgrad would you mind testing this branch for building out of the docker container. I tested on my host and using the release scripts and seems good.

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Ping the community here to see if someone else can confirm they're able to build GPU Addons from source with this PR. This isn't needed for any release, but it would be smart to merge/fix this before a full TF2 release.

**Comment by lukaszgrad** [comment]
I'm sorry @seanpmorgan for not reaching earlier. I've tried to build it and got the error during bazel build:

```
Starting local Bazel server and connecting to it...
................................................................
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1329
                _create_local_cuda_repository(repository_ctx)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1131, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 942, in _get_cuda_config
                cuda_toolkit_path(repository_ctx)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 419, in cuda_toolkit_path
                auto_configure_fail("Cannot find cuda toolkit path.")
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 343, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cuda toolkit path.
```

I have recently installed cuda 10.1 and I don't know if it's a problem, since tf-addons officialy require 10.0 version (I still have cuda 10.0 paths and installation preserved in the system).

**Comment by lukaszgrad** [comment]
Some progress has been made, it has started to build :)

```
WARNING: /home/lukasz/.cache/bazel/_bazel_lukasz/b35ea0e68412db7d60dbb10fd25e4022/external/local_config_tf/BUILD:3588:1: target 'ensorflow_framework' is both a rule and a file; please choose another name for the rule
ERROR: /home/lukasz/.cache/bazel/_bazel_lukasz/b35ea0e68412db7d60dbb10fd25e4022/external/local_config_tf/BUILD:13:12: in srcs attribute of cc_library rule @local_config_tf//:libtensorflow_framework: '@local_config_tf//:ensorflow_framework' does not produce any cc_library srcs files (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .ipp, .hxx, .inc, .S, .s, .asm, .a, .lib, .pic.a, .lo, .pic.lo, .so, .dylib, .dll, .o or .pic.o)
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: Analysis of target '@local_config_tf//:libtensorflow_framework' failed; build aborted
INFO: Elapsed time: 0.253s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by seanpmorgan** [comment]
Hmmm `ensorflow_framework` means that the shared object name was not being properly parsed here:
https://github.com/tensorflow/addons/blob/master/configure.sh#L32 (not part of this PR)

Are you running `./configure.sh`? It feels like that was ran against  TF1.13 or earlier.

**Comment by facaiy** [comment]
@lukaszgrad Hi, can you try to run `./configure.sh` as suggested by @seanpmorgan ? Thank you :-) I'd like to merge the PR if everything is OK.

**Comment by olesalscheider** [comment]
I can build GPU addons from source with this patch.

**Comment by SebastienKeroack** [comment]
`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads$ git clone https://github.com/seanpmorgan/addons.git
Cloning into 'addons'...
remote: Enumerating objects: 2706, done.
remote: Total 2706 (delta 0), reused 0 (delta 0), pack-reused 2706
Receiving objects: 100% (2706/2706), 1.42 MiB | 615.00 KiB/s, done.
Resolving deltas: 100% (1709/1709), done.
`
`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads$ cd addons`

`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads/addons$ export TF_NEED_CUDA=1`

`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads/addons$ git checkout bld-fix-and-cleanup
Branch 'bld-fix-and-cleanup' set up to track remote branch 'bld-fix-and-cleanup' from 'origin'.
Switched to a new branch 'bld-fix-and-cleanup'`

`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads/addons$ ./configure.sh
Tensorflow 2.0 will be installed if it is not already. Are You Sure? [y/n] y
Installing...
Collecting tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802 (from -r build_deps/requirements_gpu.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/12/a9/d49b70de8888e8d14e96df9cee131396ecf137d9ce4f56b6d6a9f5351941/tf_nightly_gpu_2.0_preview-2.0.0.dev20190930-cp37-cp37m-manylinux2010_x86_64.whl (393.4MB)
     |████████████████████████████████| 393.4MB 117kB/s 
Collecting tensorflow-estimator-2.0-preview (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/db/f5/790508e193121ab301cb40cada7f451c531404051ac9249f21b1f5484450/tensorflow_estimator_2.0_preview-2.0.0-py2.py3-none-any.whl (449kB)
     |████████████████████████████████| 450kB 16kB/s 
Requirement already satisfied: google-pasta>=0.1.6 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.1.7)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.33.4)
Collecting keras-applications>=1.0.8 (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Requirement already satisfied: opt-einsum>=2.3.2 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (2.3.2)
Requirement already satisfied: six>=1.10.0 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (1.12.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /home/sebastien/.local/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (1.16.4)
Requirement already satisfied: wrapt>=1.11.1 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (1.11.2)
Requirement already satisfied: absl-py>=0.7.0 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.7.1)
Requirement already satisfied: protobuf>=3.6.1 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (3.8.0)
Collecting tb-nightly<2.2.0a0,>=2.1.0a0 (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/39/b9/a15725995240548f7b9110890d9014ad5097a64ef7617866ebd86a087de2/tb_nightly-2.1.0a20190930-py3-none-any.whl (3.8MB)
     |████████████████████████████████| 3.8MB 609kB/s 
Requirement already satisfied: grpcio>=1.8.6 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (1.21.1)
Requirement already satisfied: termcolor>=1.1.0 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (1.1.0)
Requirement already satisfied: gast==0.2.2 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.2.2)
Requirement already satisfied: astor>=0.6.0 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.8.0)
Collecting keras-preprocessing>=1.0.5 (from tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: h5py in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from keras-applications>=1.0.8->tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (2.9.0)
Requirement already satisfied: setuptools in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from protobuf>=3.6.1->tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (41.0.1)
Requirement already satisfied: markdown>=2.6.8 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tb-nightly<2.2.0a0,>=2.1.0a0->tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (3.1.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages (from tb-nightly<2.2.0a0,>=2.1.0a0->tf-nightly-gpu-2.0-preview>=2.0.0.dev20190802->-r build_deps/requirements_gpu.txt (line 2)) (0.15.4)
Installing collected packages: tensorflow-estimator-2.0-preview, keras-applications, tb-nightly, keras-preprocessing, tf-nightly-gpu-2.0-preview
Successfully installed keras-applications-1.0.8 keras-preprocessing-1.1.0 tb-nightly-2.1.0a20190930 tensorflow-estimator-2.0-preview-2.0.0 tf-nightly-gpu-2.0-preview-2.0.0.dev20190930
2019-09-30 09:01:30.317963: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
2019-09-30 09:01:32.444936: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
2019-09-30 09:01:34.441189: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory`

`(tensorflow-gpu-prev) sebastien@sebastien-desktop:~/Downloads/addons$ bazel build build_pip_pkg
Starting local Bazel server and connecting to it...
WARNING: /home/sebastien/.cache/bazel/_bazel_sebastien/a0ed615a0e9d7b0ded4846f43e78b71b/external/local_config_tf/BUILD:245
3:1: target 'libtensorflow_framework.so.2' is both a rule and a file; please choose another name for the rule
DEBUG: /home/sebastien/.cache/bazel/_bazel_sebastien/a0ed615a0e9d7b0ded4846f43e78b71b/external/bazel_tools/tools/cpp/lib_c
c_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
INFO: Analyzed target //:build_pip_pkg (35 packages loaded, 362 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/sebastien/.cache/bazel/_bazel_sebastien/a0ed615a0e9d7b0ded4846f43e78b71b/sandbox
ERROR: /home/sebastien/.cache/bazel/_bazel_sebastien/a0ed615a0e9d7b0ded4846f43e78b71b/external/local_config_tf/BUILD:17:1:
 Executing genrule @local_config_tf//:tf_header_include failed (Exit 1)
cp: cannot stat '/home/sebastien/miniconda3/envs/tensorflow-gpu-prev/lib/python3.7/site-packages/tensorflow_core/include/E
igen/src/Core/arch/GPU/Half.h': No such file or directory
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/sebastien/Downloads/addons/tensorflow_addons/custom_ops/activations/BUILD:74:1 Executing genrule @local_confi
g_tf//:tf_header_include failed (Exit 1)
INFO: Elapsed time: 18.570s, Critical Path: 11.40s
INFO: 4 processes: 4 local.
FAILED: Build did NOT complete successfully`

**Comment by facaiy** [comment]
@SebastienKeroack Did you run those commands in docker container?

**Comment by facaiy** [comment]
@olesalscheider Thanks for your feedback, Niels!

**Comment by SebastienKeroack** [comment]
@facaiy No, but i'm using miniconda as environment management

**Comment by facaiy** [comment]
> Currently building GPU package from source fails outside of the docker container. 

Sorry for my oversight. I'm afraid that it might be not easy to support due to various environment, that's why we use docker container.

**Comment by lukaszgrad** [comment]
Currently got this error, ignore my last error, it was on different environment without some env vars set:

```
lukasz@grail-gpu2:~/kaggle/kaggle-recursion/tfrec/addons$ bazel build build_pip_pkg
ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1329
                _create_local_cuda_repository(repository_ctx)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1131, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 945, in _get_cuda_config
                _cudnn_version(repository_ctx, cudnn_install_base..., ...)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 606, in _cudnn_version
                _find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 901, in _find_cudnn_header_dir
                auto_configure_fail(("Cannot find cudnn.h under %s" ...))
        File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 343, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cudnn.h under /usr/lib/x86_64-linux-gnu
INFO: Elapsed time: 0.190s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
lukasz@grail-gpu2:~/kaggle/kaggle-recursion/tfrec/addons$ ls /usr/lib/x86_64-linux-gnu/cudnn.h
/usr/lib/x86_64-linux-gnu/cudnn.h
```

**Comment by seanpmorgan** [comment]
> Currently got this error, ignore my last error, it was on different environment without some env vars set:
> 
> ```
> lukasz@grail-gpu2:~/kaggle/kaggle-recursion/tfrec/addons$ bazel build build_pip_pkg
> ERROR: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1329
>                 _create_local_cuda_repository(repository_ctx)
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 1131, in _create_local_cuda_repository
>                 _get_cuda_config(repository_ctx)
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 945, in _get_cuda_config
>                 _cudnn_version(repository_ctx, cudnn_install_base..., ...)
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 606, in _cudnn_version
>                 _find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 901, in _find_cudnn_header_dir
>                 auto_configure_fail(("Cannot find cudnn.h under %s" ...))
>         File "/home/lukasz/kaggle/kaggle-recursion/tfrec/addons/build_deps/toolchains/gpu/cuda_configure.bzl", line 343, in auto_configure_fail
>                 fail(("\n%sCuda Configuration Error:%...)))
> 
> Cuda Configuration Error: Cannot find cudnn.h under /usr/lib/x86_64-linux-gnu
> INFO: Elapsed time: 0.190s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> lukasz@grail-gpu2:~/kaggle/kaggle-recursion/tfrec/addons$ ls /usr/lib/x86_64-linux-gnu/cudnn.h
> /usr/lib/x86_64-linux-gnu/cudnn.h
> ```
> 
> I tried setting CUDNN_INSTALL_PATH directly to my cuda folder, no difference.

Could you tell us where cudnn.h is located on your machine and also what the contents of your `.bazelrc` file is?

**Pull request merged**
