### PR TITLE
Moved test out of run_in_graph_and_eager_mode.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
See #1328

### CODE REVIEW

**Comment by cgarciae** [comment]
@gabrieldemarmiesse why is `test_output_shape` now outside the class?

**Comment by cgarciae** [comment]
Ah, its just an example? The idea is that we move all test outside without the decorator?

**Comment by gabrieldemarmiesse** [comment]
Long story short, `run_all_in_graph_and_eager_mode` is a private function, so we're trying to get rid of it. It also had a behavior that makes us write tests in the TF 1.x style, which is not very user friendly. We use fixtures as alternative.

**Comment by cgarciae** [comment]
If I read correctly, the idea would be to use `pytest.mark.usefixtures("maybe_run_functions_eagerly")` over each test that previously relied on `run_all_in_graph_and_eager_mode`?

**Comment by gabrieldemarmiesse** [comment]
Not necessarily. By default, tensorflow runs in eager mode. So the tests will run in eager mode. If there are some tf.function, then what is inside runs in graph mode. 

It depends on what is the objective of the test, and what is the feature you're testing. 
If the code written in a layer uses no strange control flow, like for loops or if on tensors, we don't need to run the tests in graph mode. 

If we see that there are some pieces of code where the control flow is tricky, we need to decorate with a tf.function (possibly in the test even, it's not necessary to expose a tf.function to the user) and then we use the fixture `maybe_run_functions_eagerly`. The fixture will run the test twice. Once normally, and once with all the tf.functions disabled (so full eager mode).

We need to remember that by checking with tf.function and eager, we double the running time of the test. So we shouldn't use it everywhere "just to be safe". Having fast tests is very important for the developer's experience.

We're going to add more stuff in the contributing about the fixtures that contributors can use in the tests.

**Comment by cgarciae** [comment]
I see. I mainly see the value of testing on both modes because of `Tensor.shape` behaving differently between eager and graph mode. 

Will address this tonight :)

**Comment by gabrieldemarmiesse** [comment]
I can add the decorator for this one, to ensure that the `call` method works in graph and eager mode.

**Pull request closed without merging**
