### PR TITLE
REFACOTR: Function Extraction _zero_wt_init(name)

### PR DESCRIPTION
**Pull request by marload**
Thank You!

### CODE REVIEW

**Comment by marload** [comment]
https://github.com/tensorflow/addons/blob/f03f26f8c16097cfbc36739135ea3a38b6287896/tensorflow_addons/metrics/f_scores.py#L114

This refactoring is already in use by F-Score. In my view, I think this is useful. :smile:

**Comment by bhack** [comment]
I meant if this pattern It Is used/useful in multiple place or just in multipleetrics could this function go in `utils.py` instead of redefine It multiple time?

**Comment by marload** [comment]
Oh, I see. It seems like a better way.

**Comment by bhack** [comment]
Have you seen https://github.com/tensorflow/addons/pull/2013#pullrequestreview-451060161?

**Comment by bhack** [comment]
I meant only to see https://github.com/tensorflow/addons/blob/master/tensorflow_addons/metrics/multilabel_confusion_matrix.py#L84

**Pull request closed without merging**
