### PR TITLE
Clean-up of the docker tools for local dev.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**

### CODE REVIEW

**Comment by seanpmorgan** [comment]
Uhhh GitHub actions didn't trigger? Maybe make a dummy commit (or if there is a way to trigger this please let me know).

**Comment by gabrieldemarmiesse** [comment]
Usually it happens because of an indentation issue in the yaml

**Comment by seanpmorgan** [comment]
@gabrieldemarmiesse Mostly LGTM but need to fix the conflict. Apologies for the slow review that caused it.

**Comment by gabrieldemarmiesse** [comment]
no worries

**Comment by gabrieldemarmiesse** [comment]
Should be good to go.

**Pull request merged**
