### PR TITLE
Refactor crf code to support constrained decoding

### PR DESCRIPTION
**Pull request by napsternxg**
Fixes tensorflow#607

- Implements a common function for creating `filtered_inputs` used in
`crf_multitag_sequence_score`
- This function is reused to modify the input to in
`crf_constrained_decode` to pass filtered input to `crf_decode` to
perform constrained decoding.
- Added test cases

### CODE REVIEW

**Comment by napsternxg** [comment]
@seanpmorgan @Squadrick @facaiy 
I have cleaned up the old PR #609 and moved it here. Please review it here. The changes are the same.

**Comment by gabrieldemarmiesse** [comment]
@googlebot I consent

**Comment by gabrieldemarmiesse** [comment]
I've merged master into your branch to update it and fixed any formatting/conflicts it might have. If you need to do some more modifications, please do `git pull` beforehand.

**Comment by gabrieldemarmiesse** [comment]
The pull request didn't pass the tests and have not been updated for a while. I'll be closing it. If there are changes, feel free to re-open it.

**Pull request closed without merging**
