### PR TITLE
Fix building on raspberry pi

### PR DESCRIPTION
**Pull request by DanBmh**
# Description

Fix building package on raspberry pi

## Type of change

- [x] Bug fix

# Checklist:

- [ ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running Black + Flake8
    - [ ] By running pre-commit hooks
- [ ] This PR addresses an already submitted issue for TensorFlow Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] This PR contains modifications to C++ custom-ops

# How Has This Been Tested?

Build of package in raspbian buster container did work after applying the suggested changes

### CODE REVIEW

**Comment by DanBmh** [comment]
@googlebot I signed it!

**Review by seanpmorgan — APPROVED** [review]
We're unable to test this without a ARM CI, but looks correct and shouldn't have any negative effects for the other builds we support.

Thanks for the PR!

**Comment by StuartIanNaylor** [comment]
Any chance anyone could do  aarch64 build for the pi? I tried but failed even after doing a symlink to _pywrap_tensorflow_internal

**Comment by Qengineering** [comment]
@StuartIanNaylor could you be so kind to have a look at pull request #2420, A fix for the Raspberry Pi 64-bit OS and Jetson Nanon?

**Comment by StuartIanNaylor** [comment]
sudo nano configure.py Change 2 lines to the following:-

def is_raspi_arm():
    return (os.uname()[4] == "armv7l") or (os.uname()[4] == "aarch64")  
    
    if is_macos() or is_linux():
#        write("build --copt=-mavx") <-not known in gcc aarch64 
        write("build --cxxopt=-std=c++14")
        write("build --host_cxxopt=-std=c++14")
        
 sudo ln -s /home/pi/google-kws/venv/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so /usr/lib/lib_pywrap_tensorflow_internal.so
 
 Works for Aarch64 just do the normal install after

**Pull request merged**
