### PR TITLE
Use a minimal docker image to build wheels. Fix the master branch build.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
@seanpmorgan 

That's still annoying because I wanted to add a `--mount=type=cache,dest=/root/.cache/pip` but It seems like it won't be possible.

### CODE REVIEW

**Comment by gabrieldemarmiesse** [comment]
Well well well

**Comment by gabrieldemarmiesse** [comment]
It seems that it won't work, even if we don't install the pytest dependencies (scikit-image and such).

**Comment by seanpmorgan** [comment]
@googlebot I consent.

**Comment by gabrieldemarmiesse** [comment]
Still missing #1527 to totally fix the master branch.

**Pull request merged**
