### PR TITLE
Simpler python implementation of softshrink.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
I don't know why I didn't think about using tf.where the first time, it's much easier.

### CODE REVIEW

**Comment by AakashKumarNain** [comment]
Yeap. Easier and much clear

**Comment by gabrieldemarmiesse** [comment]
@AakashKumarNain do you need me to do some changes before merging?

**Comment by AakashKumarNain** [comment]
@gabrieldemarmiesse No. LGTM. Thanks

**Comment by gabrieldemarmiesse** [comment]
@AakashKumarNain , to merge, you need to go in "Files changed" > click on review > approve > then click squash and merge

**Comment by AakashKumarNain** [comment]
LOL. I thought you just asked regarding changes only

**Comment by gabrieldemarmiesse** [comment]
I can't merge without the approval of one other maintainer. It's not a soft rule, it's actually enforced by github :p

**Comment by AakashKumarNain** [comment]
Yeah I am aware of that. That's why I am still waiting on #765

**Pull request merged**
